#pragma once
#include "pch.h"

enum class ActorType
{
	Player,
	Dino,
	Turret,
	Structure,
	Item,
	Other,
	MapActor
};

enum class StructureType
{
	SleepingBag,
	Bed,
	BunkBed,
	SmallTeleporter,
	MediumTeleporter,
	LargeTeleporter,
	AutoTurret,
	HeavyTurret,
	TekTurret,
	SmallCropPlot,
	MediumCropPlot,
	LargeCropPlot,
	ElectricalGenerator,
	TekGenerator,
	TekTransmitter,
	CryoFridge,
	CloningChamber,
	VacuumCompartment,
	Foundation,
	Wall,
	Door,
	DoorFrame,
	Ceiling,
	FenceFoundation,
	SmallStorageBox,
	LargeStorageBox,
	Vault,
	Refrigerator,
	AirConditioner,
	DedicatedStorage,
	TekForceField,
	Replicator,
	Fabricator,
	Smithy,
	MortarAndPestle,
	ChemistryBench,
	IndustrialForge,
	IndustrialGrill,
	IndustrialCookingPot,
	Grinder,
	CookingPot,
	C4Charge,
	BearTrap,
	LargeBearTrap,
	WaterMine,
	ItemCache,
	SupplyDrop,
	CaveDrop,
	Artifact,
	BeaverDam,
	BeeHive,
	Note,
	ChargeNode,
	CliffPlat,
	Nest,
	PlantX,
	LinkedStorageBox,
	TeslaCoil,
	Other,
	NONE
};

typedef int InputType;
enum InputType_
{
	InputType_None = 0,
	InputType_Alphabet = 1 << 0,
	InputType_Numbers = 1 << 1,
	InputType_Punctuation = 1 << 2,
	InputType_Special = 1 << 3,
	InputType_Function = 1 << 4
};

struct CurrentActor
{
	ActorType Type;
	StructureType StructType;
	AActor* Actor;
	FVector2D ScreenPos;
	FVector Pos;
	float distance;
	bool IsFriendly;
	bool IsDead;
	bool IsSleeping;
	bool IsVisible;
	bool OnScreen;
};

class DinoLevelPresetzzz
{
public:
	std::wstring Name;
	std::wstring Health;
	std::wstring Stamina;
	std::wstring Oxygen;
	std::wstring Food;
	std::wstring Weight;
	std::wstring Melee;

	DinoLevelPresetzzz() : Name(Xors(L"None")), Health(Xors(L"0")), Stamina(Xors(L"0")), Oxygen(Xors(L"0")), Food(Xors(L"0")), Weight(Xors(L"0")), Melee(Xors(L"0"))
	{
	}

	DinoLevelPresetzzz(std::wstring name, std::wstring Health, std::wstring Stamina, std::wstring Oxygen, std::wstring Food, std::wstring Weight, std::wstring Melee) : Name(name) , Health(Health), Stamina(Stamina), Oxygen(Oxygen), Food(Food), Weight(Weight), Melee(Melee)
	{
	}
};

struct Structure
{
	StructureType type;
	int Index;
	std::wstring descName;
	UClass* StaticStructure;
	Structure(StructureType type, std::wstring descName, UClass* StaticStructure, int index) : type(type), descName(descName), StaticStructure(StaticStructure), Index(index) {}
};

typedef struct CallServerMovePackedParams
{
	UCharacterMovementComponent* _this;
	FSavedMove_Character* NewMove;
	FSavedMove_Character* PendingMove;
	FSavedMove_Character* OldMove;
} CallServerMovePackedParams;

typedef struct HitMarker3D
{
	TimeVar HitTime;
	FVector Location;
}HitMarker3D;

namespace soundArr
{
	inline std::vector<std::string> GoodSounds;

	//inline const char* Sounds[694] = 
	//{
	//    Xors("SoundWave Engine.Default__SoundWave"),
	//    Xors("SoundWaveProcedural Engine.Default__SoundWaveProcedural"),
	//    Xors("SoundWave PW_gen_access_inventory.PW_gen_access_inventory"),
	//    Xors("SoundWave PW_GenericInvClose.PW_GenericInvClose"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_soft_12.s_creature_footstep_mat_wood_soft_12"),
	//    Xors("SoundWave s_ui_menu_press_select_heavy.s_ui_menu_press_select_heavy"),
	//    Xors("SoundWave s_ui_menu_press_cancel.s_ui_menu_press_cancel"),
	//    Xors("SoundWave s_ui_menu_press_back.s_ui_menu_press_back"),
	//    Xors("SoundWave s_menu_build_place_generic.s_menu_build_place_generic"),
	//    Xors("SoundWave s_ui_menu_press_tab_small.s_ui_menu_press_tab_small"),
	//    Xors("SoundWave s_ui_menu_press_select_light.s_ui_menu_press_select_light"),
	//    Xors("SoundWave s_menu_inventory_open.s_menu_inventory_open"),
	//    Xors("SoundWave s_menu_inventory_close.s_menu_inventory_close"),
	//    Xors("SoundWave s_ui_menu_press_select.s_ui_menu_press_select"),
	//    Xors("SoundWave s_ui_menu_press_reset.s_ui_menu_press_reset"),
	//    Xors("SoundWave UI_Error_Subtle_Deep_stereo.UI_Error_Subtle_Deep_stereo"),
	//    Xors("SoundWave s_lance_unready.s_lance_unready"),
	//    Xors("SoundWave PW_gen_clothing_unequip.PW_gen_clothing_unequip"),
	//    Xors("SoundWave PW_gen_clothing_equip.PW_gen_clothing_equip"),
	//    Xors("SoundWave PW_gen_item_break.PW_gen_item_break"),
	//    Xors("SoundWave PW_wep_attachment_apply.PW_wep_attachment_apply"),
	//    Xors("SoundWave s_weap_revolver_unequip.s_weap_revolver_unequip"),
	//    Xors("SoundWave s_tekrifle_unequip.s_tekrifle_unequip"),
	//    Xors("SoundWave s_sickle_equip.s_sickle_equip"),
	//    Xors("SoundWave s_hatchet_unequip.s_hatchet_unequip"),
	//    Xors("SoundWave PW_wep_switch_weapon.PW_wep_switch_weapon"),
	//    Xors("SoundWave PW_gen_eat_soup.PW_gen_eat_soup"),
	//    Xors("SoundWave Poop.Poop"),
	//    Xors("SoundWave s_tekrex_deactivate.s_tekrex_deactivate"),
	//    Xors("SoundWave s_gigalaser_fire.s_gigalaser_fire"),
	//    Xors("SoundWave s_tekrex_activate.s_tekrex_activate"),
	//    Xors("SoundWave s_tekturret_deactivate.s_tekturret_deactivate"),
	//    Xors("SoundWave PW_gen_creature_dismount.PW_gen_creature_dismount"),
	//    Xors("SoundWave Change_Frequency_Radio.Change_Frequency_Radio"),
	//    Xors("SoundWave s_human_lowhealth.s_human_lowhealth"),
	//    Xors("SoundWave s_lance_ready.s_lance_ready"),
	//    Xors("SoundWave s_lance_dismounted.s_lance_dismounted"),
	//    Xors("SoundWave s_tekarmor_glove_impact.s_tekarmor_glove_impact"),
	//    Xors("SoundWave s_dino_pachy_bodyfall.s_dino_pachy_bodyfall"),
	//    Xors("SoundWave UseBloodPack.UseBloodPack"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_hard_08.s_creature_footstep_mat_brushhigh_hard_08"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_hard_11.s_creature_footstep_mat_brushhigh_hard_11"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_hard_10.s_creature_footstep_mat_brushhigh_hard_10"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_hard_04.s_creature_footstep_mat_brushhigh_hard_04"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_hard_01.s_creature_footstep_mat_brushhigh_hard_01"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_hard_12.s_creature_footstep_mat_brushhigh_hard_12"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_hard_05.s_creature_footstep_mat_brushhigh_hard_05"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_hard_02.s_creature_footstep_mat_brushhigh_hard_02"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_hard_09.s_creature_footstep_mat_brushhigh_hard_09"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_medium_03.s_creature_footstep_mat_rock_medium_03"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_medium_08.s_creature_footstep_mat_rock_medium_08"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_medium_06.s_creature_footstep_mat_rock_medium_06"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_medium_01.s_creature_footstep_mat_rock_medium_01"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_medium_09.s_creature_footstep_mat_rock_medium_09"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_medium_05.s_creature_footstep_mat_rock_medium_05"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_medium_07.s_creature_footstep_mat_rock_medium_07"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_medium_10.s_creature_footstep_mat_rock_medium_10"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_medium_02.s_creature_footstep_mat_dirt_medium_02"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_medium_01.s_creature_footstep_mat_dirt_medium_01"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_medium_03.s_creature_footstep_mat_dirt_medium_03"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_medium_07.s_creature_footstep_mat_dirt_medium_07"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_medium_10.s_creature_footstep_mat_dirt_medium_10"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_medium_05.s_creature_footstep_mat_dirt_medium_05"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_medium_09.s_creature_footstep_mat_dirt_medium_09"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_medium_06.s_creature_footstep_mat_dirt_medium_06"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_medium_08.s_creature_footstep_mat_dirt_medium_08"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_medium_04.s_creature_footstep_mat_dirt_medium_04"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_hard_03.s_creature_footstep_mat_mud_hard_03"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_hard_07.s_creature_footstep_mat_mud_hard_07"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_hard_01.s_creature_footstep_mat_mud_hard_01"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_hard_02.s_creature_footstep_mat_mud_hard_02"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_hard_04.s_creature_footstep_mat_mud_hard_04"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_hard_08.s_creature_footstep_mat_mud_hard_08"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_hard_06.s_creature_footstep_mat_mud_hard_06"),
	//    Xors("SoundWave s_creature_footstep_mat_water_soft_02.s_creature_footstep_mat_water_soft_02"),
	//    Xors("SoundWave s_creature_footstep_mat_water_soft_12.s_creature_footstep_mat_water_soft_12"),
	//    Xors("SoundWave s_creature_footstep_mat_water_soft_04.s_creature_footstep_mat_water_soft_04"),
	//    Xors("SoundWave s_creature_footstep_mat_water_soft_11.s_creature_footstep_mat_water_soft_11"),
	//    Xors("SoundWave s_creature_footstep_mat_water_soft_03.s_creature_footstep_mat_water_soft_03"),
	//    Xors("SoundWave s_creature_footstep_mat_water_soft_06.s_creature_footstep_mat_water_soft_06"),
	//    Xors("SoundWave s_creature_footstep_mat_water_soft_10.s_creature_footstep_mat_water_soft_10"),
	//    Xors("SoundWave s_creature_footstep_mat_water_soft_07.s_creature_footstep_mat_water_soft_07"),
	//    Xors("SoundWave s_creature_footstep_mat_water_soft_08.s_creature_footstep_mat_water_soft_08"),
	//    Xors("SoundWave s_creature_footstep_mat_water_soft_05.s_creature_footstep_mat_water_soft_05"),
	//    Xors("SoundWave s_creature_footstep_mat_water_soft_01.s_creature_footstep_mat_water_soft_01"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_hard_08.s_creature_footstep_mat_brushlow_hard_08"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_hard_07.s_creature_footstep_mat_brushlow_hard_07"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_hard_05.s_creature_footstep_mat_brushlow_hard_05"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_hard_06.s_creature_footstep_mat_brushlow_hard_06"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_hard_03.s_creature_footstep_mat_brushlow_hard_03"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_soft_06.s_creature_footstep_mat_brushlow_soft_06"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_soft_02.s_creature_footstep_mat_brushlow_soft_02"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_soft_07.s_creature_footstep_mat_brushlow_soft_07"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_soft_11.s_creature_footstep_mat_brushlow_soft_11"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_soft_09.s_creature_footstep_mat_brushlow_soft_09"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_soft_04.s_creature_footstep_mat_brushlow_soft_04"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_soft_10.s_creature_footstep_mat_brushlow_soft_10"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_soft_03.s_creature_footstep_mat_brushlow_soft_03"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_soft_01.s_creature_footstep_mat_brushlow_soft_01"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_medium_01.s_creature_footstep_mat_mud_medium_01"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_medium_07.s_creature_footstep_mat_mud_medium_07"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_medium_03.s_creature_footstep_mat_mud_medium_03"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_medium_02.s_creature_footstep_mat_mud_medium_02"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_medium_10.s_creature_footstep_mat_mud_medium_10"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_medium_05.s_creature_footstep_mat_mud_medium_05"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_hard_07.s_creature_footstep_mat_rock_hard_07"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_hard_06.s_creature_footstep_mat_rock_hard_06"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_hard_08.s_creature_footstep_mat_rock_hard_08"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_hard_03.s_creature_footstep_mat_rock_hard_03"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_hard_04.s_creature_footstep_mat_rock_hard_04"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_hard_02.s_creature_footstep_mat_rock_hard_02"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_soft_04.s_creature_footstep_mat_wood_soft_04"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_soft_10.s_creature_footstep_mat_wood_soft_10"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_soft_09.s_creature_footstep_mat_wood_soft_09"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_soft_06.s_creature_footstep_mat_wood_soft_06"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_soft_05.s_creature_footstep_mat_wood_soft_05"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_soft_07.s_creature_footstep_mat_wood_soft_07"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_soft_02.s_creature_footstep_mat_wood_soft_02"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_medium_06.s_creature_footstep_mat_brushhigh_medium_06"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_medium_05.s_creature_footstep_mat_brushhigh_medium_05"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_medium_01.s_creature_footstep_mat_brushhigh_medium_01"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_medium_08.s_creature_footstep_mat_brushhigh_medium_08"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_medium_02.s_creature_footstep_mat_brushhigh_medium_02"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_medium_07.s_creature_footstep_mat_brushhigh_medium_07"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_medium_03.s_creature_footstep_mat_brushhigh_medium_03"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_medium_04.s_creature_footstep_mat_brushhigh_medium_04"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_medium_09.s_creature_footstep_mat_brushhigh_medium_09"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_medium_07.s_creature_footstep_mat_brushlow_medium_07"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_medium_09.s_creature_footstep_mat_brushlow_medium_09"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_medium_10.s_creature_footstep_mat_brushlow_medium_10"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_medium_03.s_creature_footstep_mat_brushlow_medium_03"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_medium_04.s_creature_footstep_mat_brushlow_medium_04"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_medium_06.s_creature_footstep_mat_brushlow_medium_06"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_medium_02.s_creature_footstep_mat_brushlow_medium_02"),
	//    Xors("SoundWave s_creature_footstep_mat_water_hard_01.s_creature_footstep_mat_water_hard_01"),
	//    Xors("SoundWave s_creature_footstep_mat_water_hard_07.s_creature_footstep_mat_water_hard_07"),
	//    Xors("SoundWave s_creature_footstep_mat_water_hard_06.s_creature_footstep_mat_water_hard_06"),
	//    Xors("SoundWave s_creature_footstep_mat_water_hard_08.s_creature_footstep_mat_water_hard_08"),
	//    Xors("SoundWave s_creature_footstep_mat_water_hard_03.s_creature_footstep_mat_water_hard_03"),
	//    Xors("SoundWave s_creature_footstep_mat_water_hard_04.s_creature_footstep_mat_water_hard_04"),
	//    Xors("SoundWave s_creature_footstep_mat_water_hard_05.s_creature_footstep_mat_water_hard_05"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_soft_05.s_creature_footstep_mat_brushhigh_soft_05"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_soft_06.s_creature_footstep_mat_brushhigh_soft_06"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_soft_08.s_creature_footstep_mat_brushhigh_soft_08"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_soft_04.s_creature_footstep_mat_brushhigh_soft_04"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_soft_07.s_creature_footstep_mat_brushhigh_soft_07"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_soft_03.s_creature_footstep_mat_brushhigh_soft_03"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_soft_01.s_creature_footstep_mat_brushhigh_soft_01"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_soft_02.s_creature_footstep_mat_brushhigh_soft_02"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_medium_10.s_creature_footstep_mat_wood_medium_10"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_medium_02.s_creature_footstep_mat_wood_medium_02"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_medium_07.s_creature_footstep_mat_wood_medium_07"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_medium_06.s_creature_footstep_mat_wood_medium_06"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_medium_04.s_creature_footstep_mat_wood_medium_04"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_medium_03.s_creature_footstep_mat_wood_medium_03"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_medium_01.s_creature_footstep_mat_wood_medium_01"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_medium_08.s_creature_footstep_mat_wood_medium_08"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_medium_05.s_creature_footstep_mat_wood_medium_05"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_medium_06.s_creature_footstep_mat_snow_medium_06"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_medium_10.s_creature_footstep_mat_snow_medium_10"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_medium_09.s_creature_footstep_mat_snow_medium_09"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_medium_05.s_creature_footstep_mat_snow_medium_05"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_medium_01.s_creature_footstep_mat_snow_medium_01"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_medium_04.s_creature_footstep_mat_snow_medium_04"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_medium_02.s_creature_footstep_mat_snow_medium_02"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_medium_07.s_creature_footstep_mat_snow_medium_07"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_medium_08.s_creature_footstep_mat_snow_medium_08"),
	//    Xors("SoundWave s_creature_footstep_mat_water_medium_09.s_creature_footstep_mat_water_medium_09"),
	//    Xors("SoundWave s_creature_footstep_mat_water_medium_03.s_creature_footstep_mat_water_medium_03"),
	//    Xors("SoundWave s_creature_footstep_mat_water_medium_02.s_creature_footstep_mat_water_medium_02"),
	//    Xors("SoundWave s_creature_footstep_mat_water_medium_07.s_creature_footstep_mat_water_medium_07"),
	//    Xors("SoundWave s_creature_footstep_mat_water_medium_01.s_creature_footstep_mat_water_medium_01"),
	//    Xors("SoundWave s_creature_footstep_mat_water_medium_04.s_creature_footstep_mat_water_medium_04"),
	//    Xors("SoundWave s_creature_footstep_mat_water_medium_08.s_creature_footstep_mat_water_medium_08"),
	//    Xors("SoundWave s_creature_footstep_mat_water_medium_06.s_creature_footstep_mat_water_medium_06"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_soft_12.s_creature_footstep_mat_rock_soft_12"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_soft_07.s_creature_footstep_mat_rock_soft_07"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_soft_03.s_creature_footstep_mat_rock_soft_03"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_soft_04.s_creature_footstep_mat_rock_soft_04"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_soft_06.s_creature_footstep_mat_rock_soft_06"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_soft_09.s_creature_footstep_mat_rock_soft_09"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_soft_02.s_creature_footstep_mat_rock_soft_02"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_soft_10.s_creature_footstep_mat_rock_soft_10"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_soft_08.s_creature_footstep_mat_rock_soft_08"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_soft_01.s_creature_footstep_mat_rock_soft_01"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_hard_01.s_creature_footstep_mat_snow_hard_01"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_hard_05.s_creature_footstep_mat_snow_hard_05"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_hard_08.s_creature_footstep_mat_snow_hard_08"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_hard_02.s_creature_footstep_mat_snow_hard_02"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_hard_07.s_creature_footstep_mat_snow_hard_07"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_hard_06.s_creature_footstep_mat_snow_hard_06"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_hard_04.s_creature_footstep_mat_snow_hard_04"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_soft_09.s_creature_footstep_mat_snow_soft_09"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_soft_10.s_creature_footstep_mat_snow_soft_10"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_soft_04.s_creature_footstep_mat_snow_soft_04"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_soft_05.s_creature_footstep_mat_snow_soft_05"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_soft_03.s_creature_footstep_mat_snow_soft_03"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_soft_06.s_creature_footstep_mat_snow_soft_06"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_soft_08.s_creature_footstep_mat_snow_soft_08"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_soft_02.s_creature_footstep_mat_snow_soft_02"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_soft_03.s_creature_footstep_mat_grass_soft_03"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_soft_01.s_creature_footstep_mat_grass_soft_01"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_soft_08.s_creature_footstep_mat_grass_soft_08"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_soft_06.s_creature_footstep_mat_grass_soft_06"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_soft_10.s_creature_footstep_mat_grass_soft_10"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_soft_09.s_creature_footstep_mat_grass_soft_09"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_soft_02.s_creature_footstep_mat_grass_soft_02"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_soft_07.s_creature_footstep_mat_grass_soft_07"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_soft_12.s_creature_footstep_mat_grass_soft_12"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_soft_05.s_creature_footstep_mat_grass_soft_05"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_soft_04.s_creature_footstep_mat_grass_soft_04"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_hard_05.s_creature_footstep_mat_wood_hard_05"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_hard_03.s_creature_footstep_mat_wood_hard_03"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_hard_06.s_creature_footstep_mat_wood_hard_06"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_hard_04.s_creature_footstep_mat_wood_hard_04"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_hard_07.s_creature_footstep_mat_wood_hard_07"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_hard_01.s_creature_footstep_mat_wood_hard_01"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_soft_05.s_creature_footstep_mat_dirt_soft_05"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_soft_03.s_creature_footstep_mat_dirt_soft_03"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_soft_08.s_creature_footstep_mat_dirt_soft_08"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_soft_11.s_creature_footstep_mat_dirt_soft_11"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_soft_07.s_creature_footstep_mat_dirt_soft_07"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_soft_01.s_creature_footstep_mat_dirt_soft_01"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_soft_09.s_creature_footstep_mat_dirt_soft_09"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_soft_02.s_creature_footstep_mat_dirt_soft_02"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_soft_10.s_creature_footstep_mat_dirt_soft_10"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_soft_12.s_creature_footstep_mat_dirt_soft_12"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_medium_05.s_creature_footstep_mat_grass_medium_05"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_medium_03.s_creature_footstep_mat_grass_medium_03"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_medium_01.s_creature_footstep_mat_grass_medium_01"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_medium_02.s_creature_footstep_mat_grass_medium_02"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_medium_06.s_creature_footstep_mat_grass_medium_06"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_medium_04.s_creature_footstep_mat_grass_medium_04"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_medium_09.s_creature_footstep_mat_grass_medium_09"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_hard_05.s_creature_footstep_mat_metal_hard_05"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_hard_03.s_creature_footstep_mat_metal_hard_03"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_hard_01.s_creature_footstep_mat_metal_hard_01"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_hard_04.s_creature_footstep_mat_metal_hard_04"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_hard_02.s_creature_footstep_mat_metal_hard_02"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_hard_07.s_creature_footstep_mat_metal_hard_07"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_hard_06.s_creature_footstep_mat_metal_hard_06"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_hard_08.s_creature_footstep_mat_metal_hard_08"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_hard_05.s_creature_footstep_mat_dirt_hard_05"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_hard_03.s_creature_footstep_mat_dirt_hard_03"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_hard_07.s_creature_footstep_mat_dirt_hard_07"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_hard_02.s_creature_footstep_mat_dirt_hard_02"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_hard_06.s_creature_footstep_mat_dirt_hard_06"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_hard_04.s_creature_footstep_mat_dirt_hard_04"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_medium_06.s_creature_footstep_mat_metal_medium_06"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_medium_02.s_creature_footstep_mat_metal_medium_02"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_medium_07.s_creature_footstep_mat_metal_medium_07"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_medium_09.s_creature_footstep_mat_metal_medium_09"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_medium_03.s_creature_footstep_mat_metal_medium_03"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_medium_01.s_creature_footstep_mat_metal_medium_01"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_medium_10.s_creature_footstep_mat_metal_medium_10"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_medium_04.s_creature_footstep_mat_metal_medium_04"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_medium_05.s_creature_footstep_mat_metal_medium_05"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_soft_04.s_creature_footstep_mat_metal_soft_04"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_soft_10.s_creature_footstep_mat_metal_soft_10"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_soft_09.s_creature_footstep_mat_metal_soft_09"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_soft_01.s_creature_footstep_mat_metal_soft_01"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_soft_07.s_creature_footstep_mat_metal_soft_07"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_soft_03.s_creature_footstep_mat_metal_soft_03"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_soft_11.s_creature_footstep_mat_metal_soft_11"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_soft_05.s_creature_footstep_mat_metal_soft_05"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_soft_08.s_creature_footstep_mat_metal_soft_08"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_soft_06.s_creature_footstep_mat_metal_soft_06"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_soft_02.s_creature_footstep_mat_metal_soft_02"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_soft_12.s_creature_footstep_mat_mud_soft_12"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_soft_11.s_creature_footstep_mat_mud_soft_11"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_soft_06.s_creature_footstep_mat_mud_soft_06"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_soft_07.s_creature_footstep_mat_mud_soft_07"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_soft_02.s_creature_footstep_mat_mud_soft_02"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_soft_09.s_creature_footstep_mat_mud_soft_09"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_soft_03.s_creature_footstep_mat_mud_soft_03"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_soft_05.s_creature_footstep_mat_mud_soft_05"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_soft_10.s_creature_footstep_mat_mud_soft_10"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_soft_04.s_creature_footstep_mat_mud_soft_04"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_soft_08.s_creature_footstep_mat_mud_soft_08"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_hard_01.s_creature_footstep_mat_grass_hard_01"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_hard_06.s_creature_footstep_mat_grass_hard_06"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_hard_07.s_creature_footstep_mat_grass_hard_07"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_hard_05.s_creature_footstep_mat_grass_hard_05"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_hard_04.s_creature_footstep_mat_grass_hard_04"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_hard_03.s_creature_footstep_mat_grass_hard_03"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_hard_08.s_creature_footstep_mat_grass_hard_08"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_hard_02.s_creature_footstep_mat_grass_hard_02"),
	//    Xors("SoundWave PW_gen_creature_mount.PW_gen_creature_mount"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_hard_07.s_creature_footstep_mat_brushhigh_hard_07"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_hard_03.s_creature_footstep_mat_brushhigh_hard_03"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_hard_06.s_creature_footstep_mat_brushhigh_hard_06"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_medium_04.s_creature_footstep_mat_rock_medium_04"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_medium_02.s_creature_footstep_mat_rock_medium_02"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_hard_05.s_creature_footstep_mat_mud_hard_05"),
	//    Xors("SoundWave s_creature_footstep_mat_water_soft_09.s_creature_footstep_mat_water_soft_09"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_hard_04.s_creature_footstep_mat_brushlow_hard_04"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_hard_01.s_creature_footstep_mat_brushlow_hard_01"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_hard_02.s_creature_footstep_mat_brushlow_hard_02"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_soft_08.s_creature_footstep_mat_brushlow_soft_08"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_soft_05.s_creature_footstep_mat_brushlow_soft_05"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_soft_12.s_creature_footstep_mat_brushlow_soft_12"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_medium_04.s_creature_footstep_mat_mud_medium_04"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_medium_09.s_creature_footstep_mat_mud_medium_09"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_medium_06.s_creature_footstep_mat_mud_medium_06"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_medium_08.s_creature_footstep_mat_mud_medium_08"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_hard_05.s_creature_footstep_mat_rock_hard_05"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_hard_01.s_creature_footstep_mat_rock_hard_01"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_soft_11.s_creature_footstep_mat_wood_soft_11"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_soft_01.s_creature_footstep_mat_wood_soft_01"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_soft_03.s_creature_footstep_mat_wood_soft_03"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_soft_08.s_creature_footstep_mat_wood_soft_08"),
	//    Xors("SoundWave s_creature_footstep_mat_brushhigh_medium_10.s_creature_footstep_mat_brushhigh_medium_10"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_medium_08.s_creature_footstep_mat_brushlow_medium_08"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_medium_05.s_creature_footstep_mat_brushlow_medium_05"),
	//    Xors("SoundWave s_creature_footstep_mat_brushlow_medium_01.s_creature_footstep_mat_brushlow_medium_01"),
	//    Xors("SoundWave s_creature_footstep_mat_water_hard_02.s_creature_footstep_mat_water_hard_02"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_medium_09.s_creature_footstep_mat_wood_medium_09"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_medium_03.s_creature_footstep_mat_snow_medium_03"),
	//    Xors("SoundWave s_creature_footstep_mat_water_medium_05.s_creature_footstep_mat_water_medium_05"),
	//    Xors("SoundWave s_creature_footstep_mat_water_medium_10.s_creature_footstep_mat_water_medium_10"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_soft_11.s_creature_footstep_mat_rock_soft_11"),
	//    Xors("SoundWave s_creature_footstep_mat_rock_soft_05.s_creature_footstep_mat_rock_soft_05"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_hard_03.s_creature_footstep_mat_snow_hard_03"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_soft_07.s_creature_footstep_mat_snow_soft_07"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_soft_01.s_creature_footstep_mat_snow_soft_01"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_soft_11.s_creature_footstep_mat_snow_soft_11"),
	//    Xors("SoundWave s_creature_footstep_mat_snow_soft_12.s_creature_footstep_mat_snow_soft_12"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_soft_11.s_creature_footstep_mat_grass_soft_11"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_hard_02.s_creature_footstep_mat_wood_hard_02"),
	//    Xors("SoundWave s_creature_footstep_mat_wood_hard_08.s_creature_footstep_mat_wood_hard_08"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_soft_04.s_creature_footstep_mat_dirt_soft_04"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_medium_07.s_creature_footstep_mat_grass_medium_07"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_medium_08.s_creature_footstep_mat_grass_medium_08"),
	//    Xors("SoundWave s_creature_footstep_mat_grass_medium_10.s_creature_footstep_mat_grass_medium_10"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_hard_01.s_creature_footstep_mat_dirt_hard_01"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_hard_08.s_creature_footstep_mat_dirt_hard_08"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_medium_08.s_creature_footstep_mat_metal_medium_08"),
	//    Xors("SoundWave s_creature_footstep_mat_metal_soft_12.s_creature_footstep_mat_metal_soft_12"),
	//    Xors("SoundWave s_creature_footstep_mat_mud_soft_01.s_creature_footstep_mat_mud_soft_01"),
	//    Xors("SoundWave s_tapejara_bodyfall.s_tapejara_bodyfall"),
	//    Xors("SoundWave PW_dilo_spit_flying_lp.PW_dilo_spit_flying_lp"),
	//    Xors("SoundWave UseBloodExtractor.UseBloodExtractor"),
	//    Xors("SoundWave Equip_Saddle_Sound.Equip_Saddle_Sound"),
	//    Xors("SoundWave s_footstep_sand_land.s_footstep_sand_land"),
	//    Xors("SoundWave s_male_run_3.s_male_run_3"),
	//    Xors("SoundWave s_footstep_mud_09.s_footstep_mud_09"),
	//    Xors("SoundWave SpawnShort.SpawnShort"),
	//    Xors("SoundWave SpawnIn.SpawnIn"),
	//    Xors("SoundWave PW_wep_attachment_unapply.PW_wep_attachment_unapply"),
	//    Xors("SoundWave s_creature_footstep_mat_dirt_soft_06.s_creature_footstep_mat_dirt_soft_06"),
	//    Xors("SoundWave s_cart_rolling_loop.s_cart_rolling_loop"),
	//    Xors("SoundWave PW_gen_male_eat.PW_gen_male_eat"),
	//    Xors("SoundWave PW_wep_exit_sights.PW_wep_exit_sights"),
	//    Xors("SoundWave PW_wep_enter_sights.PW_wep_enter_sights"),
	//    Xors("SoundWave PW_wep_torch_fire_lp.PW_wep_torch_fire_lp"),
	//    Xors("SoundWave PW_gen_male_drink.PW_gen_male_drink"),
	//    Xors("SoundWave PW_GenericInvAccess.PW_GenericInvAccess"),
	//    Xors("SoundWave s_ui_menu_press_button_large.s_ui_menu_press_button_large"),
	//    Xors("SoundWave s_ui_menu_press_tab.s_ui_menu_press_tab"),
	//    Xors("SoundWave s_ui_menu_press_pulldown.s_ui_menu_press_pulldown"),
	//    Xors("SoundWave s_amb_cave_wind_1.s_amb_cave_wind_1"),
	//    Xors("SoundWave s_supplycrate_inventory.s_supplycrate_inventory"),
	//    Xors("SoundWave RainAmb.RainAmb"),
	//    Xors("SoundWave PW_amb_cave.PW_amb_cave"),
	//    Xors("SoundWave GC_ARK_Center_SpawnIn_v1.GC_ARK_Center_SpawnIn_v1"),
	//    Xors("SoundWave RainAmbSnow.RainAmbSnow"),
	//    Xors("SoundWave PW_notify_level_available.PW_notify_level_available"),
	//    Xors("SoundWave Thunder.Thunder"),
	//    Xors("SoundWave SpawnReconnection_TheCenter.SpawnReconnection_TheCenter"),
	//    Xors("SoundWave CaveAmbience.CaveAmbience"),
	//    Xors("SoundWave GC_ARK_Center_SpawnIn_Short.GC_ARK_Center_SpawnIn_Short"),
	//    Xors("SoundWave s_amb_ice_move.s_amb_ice_move"),
	//    Xors("SoundWave s_amb_cave_tight.s_amb_cave_tight"),
	//    Xors("SoundWave Landscape_WindTrees01.Landscape_WindTrees01"),
	//    Xors("SoundWave AssaultRifle_ShotEnd02_Stereo.AssaultRifle_ShotEnd02_Stereo"),
	//    Xors("SoundWave s_impact_punch_snow_04.s_impact_punch_snow_04"),
	//    Xors("SoundWave AssaultRifle_ShotEnd04.AssaultRifle_ShotEnd04"),
	//    Xors("SoundWave Weapon_AssaultRifle_Empty02_Stereo.Weapon_AssaultRifle_Empty02_Stereo"),
	//    Xors("SoundWave Weapon_AssaultRifle_Empty03.Weapon_AssaultRifle_Empty03"),
	//    Xors("SoundWave s_tree_harvest_05.s_tree_harvest_05"),
	//    Xors("SoundWave s_creature_bodyfall_large_04.s_creature_bodyfall_large_04"),
	//    Xors("SoundWave s_vrboss_bots_death_01.s_vrboss_bots_death_01"),
	//    Xors("SoundWave s_gigalaser_impact_3.s_gigalaser_impact_3"),
	//    Xors("SoundWave s_impact_weapon_stone_02.s_impact_weapon_stone_02"),
	//    Xors("SoundWave s_whip_strike_4.s_whip_strike_4"),
	//    Xors("SoundWave s_bullet_impact_sand_3.s_bullet_impact_sand_3"),
	//    Xors("SoundWave s_chainsaw_impact_flesh_3.s_chainsaw_impact_flesh_3"),
	//    Xors("SoundWave s_chainsaw_impact_flesh_2.s_chainsaw_impact_flesh_2"),
	//    Xors("SoundWave s_pick_impact_wood_02.s_pick_impact_wood_02"),
	//    Xors("SoundWave s_pick_impact_rock_05.s_pick_impact_rock_05"),
	//    Xors("SoundWave PW_wep_arrow_hit_metal_04.PW_wep_arrow_hit_metal_04"),
	//    Xors("SoundWave s_bullet_impact_flesh_4.s_bullet_impact_flesh_4"),
	//    Xors("SoundWave s_pick_impact_metal_01.s_pick_impact_metal_01"),
	//    Xors("SoundWave s_bullet_impact_water_3.s_bullet_impact_water_3"),
	//    Xors("SoundWave s_bullet_impact_metal_4.s_bullet_impact_metal_4"),
	//    Xors("SoundWave s_bullet_impact_rock_5.s_bullet_impact_rock_5"),
	//    Xors("SoundWave s_bullet_impact_wood_4.s_bullet_impact_wood_4"),
	//    Xors("SoundWave s_pick_impact_leaves_04.s_pick_impact_leaves_04"),
	//    Xors("SoundWave s_tile_thatch_build_05.s_tile_thatch_build_05"),
	//    Xors("SoundWave s_impact_weapon_metal_02.s_impact_weapon_metal_02"),
	//    Xors("SoundWave s_creature_bodyfall_medium_02.s_creature_bodyfall_medium_02"),
	//    Xors("SoundWave s_creature_footstep_huge_land_06.s_creature_footstep_huge_land_06"),
	//    Xors("SoundWave s_moth_wingflap_4.s_moth_wingflap_4"),
	//    Xors("SoundWave s_creature_bodyfall_small_04.s_creature_bodyfall_small_04"),
	//    Xors("SoundWave PW_mega_move_water_05.PW_mega_move_water_05"),
	//    Xors("SoundWave s_creature_footstep_med_land_04.s_creature_footstep_med_land_04"),
	//    Xors("SoundWave s_creature_footstep_small_land_07.s_creature_footstep_small_land_07"),
	//    Xors("SoundWave s_impact_electric_3.s_impact_electric_3"),
	//    Xors("SoundWave s_splash_enter_10_04.s_splash_enter_10_04"),
	//    Xors("SoundWave s_foley_whoosh_large_06.s_foley_whoosh_large_06"),
	//    Xors("SoundWave s_rock_harvest_08.s_rock_harvest_08"),
	//    Xors("SoundWave s_cart_impact_medium_02.s_cart_impact_medium_02"),
	//    Xors("SoundWave s_splash_l_j_03.s_splash_l_j_03"),
	//    Xors("SoundWave s_splash_m_l_05.s_splash_m_l_05"),
	//    Xors("SoundWave s_splash_h_w_02.s_splash_h_w_02"),
	//    Xors("SoundWave s_splash_m_w_01.s_splash_m_w_01"),
	//    Xors("SoundWave s_splash_l_l_05.s_splash_l_l_05"),
	//    Xors("SoundWave s_splash_m_r_02.s_splash_m_r_02"),
	//    Xors("SoundWave PW_gen_harvest_stone_02.PW_gen_harvest_stone_02"),
	//    Xors("SoundWave PW_wep_bullet_impact_metal_01.PW_wep_bullet_impact_metal_01"),
	//    Xors("SoundWave PW_wep_torch_fire_swing_01.PW_wep_torch_fire_swing_01"),
	//    Xors("SoundWave s_impact_punch_glass_03.s_impact_punch_glass_03"),
	//    Xors("SoundWave s_impact_punch_lava_06.s_impact_punch_lava_06"),
	//    Xors("SoundWave s_weapon_fist_impact_flesh_05.s_weapon_fist_impact_flesh_05"),
	//    Xors("SoundWave s_weapon_fist_impact_stone_05.s_weapon_fist_impact_stone_05"),
	//    Xors("SoundWave s_impact_punch_dirt_08.s_impact_punch_dirt_08"),
	//    Xors("SoundWave s_impact_punch_grass_01.s_impact_punch_grass_01"),
	//    Xors("SoundWave s_fists_impact_water_2.s_fists_impact_water_2"),
	//    Xors("SoundWave s_weapon_fist_impact_wood_05.s_weapon_fist_impact_wood_05"),
	//    Xors("SoundWave s_weapon_fist_impact_metal_01.s_weapon_fist_impact_metal_01"),
	//    Xors("SoundWave s_foley_punch_2.s_foley_punch_2"),
	//    Xors("SoundWave s_whip_impact_3.s_whip_impact_3"),
	//    Xors("SoundWave PW_gen_ladder_climb_01.PW_gen_ladder_climb_01"),
	//    Xors("SoundWave s_foley_whoosh_small_01.s_foley_whoosh_small_01"),
	//    Xors("SoundWave s_foley_cloth_sprint_07.s_foley_cloth_sprint_07"),
	//    Xors("SoundWave s_footstep_stone_land_05.s_footstep_stone_land_05"),
	//    Xors("SoundWave s_footstep_snow_land_04.s_footstep_snow_land_04"),
	//    Xors("SoundWave s_footstep_grass_land_04.s_footstep_grass_land_04"),
	//    Xors("SoundWave s_footstep_dirt_walk_08.s_footstep_dirt_walk_08"),
	//    Xors("SoundWave s_footstep_mud_07.s_footstep_mud_07"),
	//    Xors("SoundWave s_footstep_acid_05.s_footstep_acid_05"),
	//    Xors("SoundWave s_footstep_lava_06.s_footstep_lava_06"),
	//    Xors("SoundWave s_foley_cloth_turn_01.s_foley_cloth_turn_01"),
	//    Xors("SoundWave s_foley_cloth_climb_01.s_foley_cloth_climb_01"),
	//    Xors("SoundWave s_foley_cloth_land_04.s_foley_cloth_land_04"),
	//    Xors("SoundWave s_foley_cloth_swing_04.s_foley_cloth_swing_04"),
	//    Xors("SoundWave s_foley_cloth_jump_06_R.s_foley_cloth_jump_06_R"),
	//    Xors("SoundWave s_foley_cloth_stab_04.s_foley_cloth_stab_04"),
	//    Xors("SoundWave s_foley_cloth_walk_10.s_foley_cloth_walk_10"),
	//    Xors("SoundWave s_foley_cloth_generic_quick_02.s_foley_cloth_generic_quick_02"),
	//    Xors("SoundWave s_foley_swim_03.s_foley_swim_03"),
	//    Xors("SoundWave s_footstep_stone_walk_05.s_footstep_stone_walk_05"),
	//    Xors("SoundWave s_footstep_brush_land_05.s_footstep_brush_land_05"),
	//    Xors("SoundWave s_footstep_grass_walk_01.s_footstep_grass_walk_01"),
	//    Xors("SoundWave s_footstep_brush_walk_02.s_footstep_brush_walk_02"),
	//    Xors("SoundWave s_footstep_snow_walk_04.s_footstep_snow_walk_04"),
	//    Xors("SoundWave s_footstep_water_10.s_footstep_water_10"),
	//    Xors("SoundWave s_footstep_rock_walk_14.s_footstep_rock_walk_14"),
	//    Xors("SoundWave s_footstep_sand_4.s_footstep_sand_4"),
	//    Xors("SoundWave s_footstep_metal_walk_01.s_footstep_metal_walk_01"),
	//    Xors("SoundWave s_footstep_woodsolid_land_08.s_footstep_woodsolid_land_08"),
	//    Xors("SoundWave s_foley_swim_splash_03.s_foley_swim_splash_03"),
	//    Xors("SoundWave s_foley_cloth_generic_short_05.s_foley_cloth_generic_short_05"),
	//    Xors("SoundWave s_splash_m_j_01.s_splash_m_j_01"),
	//    Xors("SoundWave s_footstep_dirt_land_02.s_footstep_dirt_land_02"),
	//    Xors("SoundWave s_footstep_rock_land_03.s_footstep_rock_land_03"),
	//    Xors("SoundWave s_footstep_woodsolid_walk_11.s_footstep_woodsolid_walk_11"),
	//    Xors("SoundWave s_splash_enter_8_03.s_splash_enter_8_03"),
	//    Xors("SoundWave s_splash_enter_9_02.s_splash_enter_9_02"),
	//    Xors("SoundWave s_splash_l_w_03.s_splash_l_w_03"),
	//    Xors("SoundWave s_splash_l_l_02.s_splash_l_l_02"),
	//    Xors("SoundWave s_tile_wood_demolish_02.s_tile_wood_demolish_02"),
	//    Xors("SoundWave s_splash_l_r_01.s_splash_l_r_01"),
	//    Xors("SoundWave s_creature_bodyfall_smallest_02.s_creature_bodyfall_smallest_02"),
	//    Xors("SoundWave s_creature_footstep_large_land_07.s_creature_footstep_large_land_07"),
	//    Xors("SoundWave s_creature_footstep_tiny_land_07.s_creature_footstep_tiny_land_07"),
	//    Xors("SoundWave Turkey_Mumble_1.Turkey_Mumble_1"),
	//    Xors("SoundWave s_tile_stone_demolish_02.s_tile_stone_demolish_02"),
	//    Xors("SoundWave PW_gen_harvest_stone_05.PW_gen_harvest_stone_05"),
	//    Xors("SoundWave PW_wep_arrow_hit_wood_01.PW_wep_arrow_hit_wood_01"),
	//    Xors("SoundWave s_flamethrower_burning_2.s_flamethrower_burning_2"),
	//    Xors("SoundWave PW_gen_harvest_stone_04.PW_gen_harvest_stone_04"),
	//    Xors("SoundWave PW_gen_axe_wood_hit_04.PW_gen_axe_wood_hit_04"),
	//    Xors("SoundWave s_fists_impact_metal_3.s_fists_impact_metal_3"),
	//    Xors("SoundWave s_fists_impact_metal_2.s_fists_impact_metal_2"),
	//    Xors("SoundWave s_fists_impact_metal_1.s_fists_impact_metal_1"),
	//    Xors("SoundWave PW_gen_axe_wood_hit_02.PW_gen_axe_wood_hit_02"),
	//    Xors("SoundWave PW_gen_axe_wood_hit_03.PW_gen_axe_wood_hit_03"),
	//    Xors("SoundWave s_foley_whoosh_small_02.s_foley_whoosh_small_02"),
	//    Xors("SoundWave s_foley_cloth_generic_medium_04.s_foley_cloth_generic_medium_04"),
	//    Xors("SoundWave s_foley_cloth_pullback_04.s_foley_cloth_pullback_04"),
	//    Xors("SoundWave s_footstep_metal_land_01.s_footstep_metal_land_01"),
	//    Xors("SoundWave s_male_drown_4.s_male_drown_4"),
	//    Xors("SoundWave s_male_cold_5.s_male_cold_5"),
	//    Xors("SoundWave s_male_hurt_8.s_male_hurt_8"),
	//    Xors("SoundWave s_male_hot_2.s_male_hot_2"),
	//    Xors("SoundWave s_male_suffer_1.s_male_suffer_1"),
	//    Xors("SoundWave s_male_death_1.s_male_death_1"),
	//    Xors("SoundWave s_footstep_water_land_4.s_footstep_water_land_4"),
	//    Xors("SoundWave ARK_Mountain_Night_Light.ARK_Mountain_Night_Light"),
	//    Xors("SoundWave ARK_Swamp_Day_Light.ARK_Swamp_Day_Light"),
	//    Xors("SoundWave ARK_Mountain_Night.ARK_Mountain_Night"),
	//    Xors("SoundWave ARK_Cave.ARK_Cave"),
	//    Xors("SoundWave ARK_Mountain_Day.ARK_Mountain_Day"),
	//    Xors("SoundWave ARK_Ocean.ARK_Ocean"),
	//    Xors("SoundWave ARK_Grassland_Day_Light.ARK_Grassland_Day_Light"),
	//    Xors("SoundWave ARK_Swamp_Day.ARK_Swamp_Day"),
	//    Xors("SoundWave ARK_Swamp_Night_Light.ARK_Swamp_Night_Light"),
	//    Xors("SoundWave ARK_Jungle_Day.ARK_Jungle_Day"),
	//    Xors("SoundWave ARK_Jungle_Night.ARK_Jungle_Night"),
	//    Xors("SoundWave ARK_Grassland_Night_Light.ARK_Grassland_Night_Light"),
	//    Xors("SoundWave ARK_Mountain_Day_Light.ARK_Mountain_Day_Light"),
	//    Xors("SoundWave ARK_Grassland_Night.ARK_Grassland_Night"),
	//    Xors("SoundWave ARK_Jungle_Day_Light.ARK_Jungle_Day_Light"),
	//    Xors("SoundWave ARK_Jungle_Night_Light.ARK_Jungle_Night_Light"),
	//    Xors("SoundWave ARK_Ocean_Light.ARK_Ocean_Light"),
	//    Xors("SoundWave ARK_Cave_Light.ARK_Cave_Light"),
	//    Xors("SoundWave ARK_Swamp_Night.ARK_Swamp_Night"),
	//    Xors("SoundWave ARK_Grassland_Day.ARK_Grassland_Day"),
	//    Xors("SoundWave s_tek_cloningchamber_finish.s_tek_cloningchamber_finish"),
	//    Xors("SoundWave ARK_TransitionToNoon.ARK_TransitionToNoon"),
	//    Xors("SoundWave ARK_TransitionToMorning.ARK_TransitionToMorning"),
	//    Xors("SoundWave s_sandstorm_inside.s_sandstorm_inside"),
	//    Xors("SoundWave ARK_TransitionToNight.ARK_TransitionToNight"),
	//    Xors("SoundWave s_weather_rain_light.s_weather_rain_light"),
	//    Xors("SoundWave Sci-Fi_Close_Holographic_Player_Inventory_Menu.Sci-Fi_Close_Holographic_Player_Inventory_Menu"),
	//    Xors("SoundWave s_teleporter_activate.s_teleporter_activate"),
	//    Xors("SoundWave BrownianNoise_1.BrownianNoise_1"),
	//    Xors("SoundWave BrownianNoise_2.BrownianNoise_2"),
	//    Xors("SoundWave BrownianNoise_4.BrownianNoise_4"),
	//    Xors("SoundWave BrownianNoise_3.BrownianNoise_3"),
	//    Xors("SoundWave Wind_Whistling.Wind_Whistling"),
	//    Xors("SoundWave s_weather_rain_layer_04.s_weather_rain_layer_04"),
	//    Xors("SoundWave s_teleporter_transport.s_teleporter_transport"),
	//    Xors("SoundWave s_teleporter_buildup.s_teleporter_buildup"),
	//    Xors("SoundWave s_teleporter_beam.s_teleporter_beam"),
	//    Xors("SoundWave PW_amb_electrical_dissipate.PW_amb_electrical_dissipate"),
	//    Xors("SoundWave s_sandstorm_outside.s_sandstorm_outside"),
	//    Xors("SoundWave s_rocketlauncher_projectile_impact.s_rocketlauncher_projectile_impact"),
	//    Xors("SoundWave s_heatwave.s_heatwave"),
	//    Xors("SoundWave PW_gen_activate_console.PW_gen_activate_console"),
	//    Xors("SoundWave s_menu_build_place_start.s_menu_build_place_start"),
	//    Xors("SoundWave s_ui_inventory_move_remove.s_ui_inventory_move_remove"),
	//    Xors("SoundWave s_ui_item_craft_begin.s_ui_item_craft_begin"),
	//    Xors("SoundWave UI_Click_Distinct_mono.UI_Click_Distinct_mono"),
	//    Xors("SoundWave s_menu_build_place_cancel.s_menu_build_place_cancel"),
	//    Xors("SoundWave s_ui_wheel_hover.s_ui_wheel_hover"),
	//    Xors("SoundWave s_ui_item_craft_queue.s_ui_item_craft_queue"),
	//    Xors("SoundWave s_menu_attribute_all.s_menu_attribute_all"),
	//    Xors("SoundWave s_menu_generic_error.s_menu_generic_error"),
	//    Xors("SoundWave UI_Switch_Dirty_Bright_stereo.UI_Switch_Dirty_Bright_stereo"),
	//    Xors("SoundWave s_ui_inventory_move_place.s_ui_inventory_move_place"),
	//    Xors("SoundWave s_ui_item_craft_finish.s_ui_item_craft_finish"),
	//    Xors("SoundWave s_ui_item_craft_cancel.s_ui_item_craft_cancel"),
	//    Xors("SoundWave s_menu_build_place_fail.s_menu_build_place_fail"),
	//    Xors("SoundWave s_menu_build_place_rotation.s_menu_build_place_rotation"),
	//    Xors("SoundWave s_menu_engram.s_menu_engram"),
	//    Xors("SoundWave UITutorial.UITutorial"),
	//    Xors("SoundWave TekClickOff.TekClickOff"),
	//    Xors("SoundWave TekClickOn.TekClickOn"),
	//    Xors("SoundWave s_ui_item_craft_queue_add.s_ui_item_craft_queue_add"),
	//    Xors("SoundWave s_ui_inventory_move_pickup.s_ui_inventory_move_pickup"),
	//    Xors("SoundWave s_ui_wheel_press_processing_end.s_ui_wheel_press_processing_end"),
	//    Xors("SoundWave s_menu_attribute.s_menu_attribute"),
	//    Xors("SoundWave UI_Click_Deep_mono.UI_Click_Deep_mono"),
	//    Xors("SoundWave s_ui_stat_apply.s_ui_stat_apply"),
	//    Xors("SoundWave s_ui_stat_engram.s_ui_stat_engram"),
	//    Xors("SoundWave s_bow_arrow_pickup.s_bow_arrow_pickup"),
	//    Xors("SoundWave s_scroll_close.s_scroll_close"),
	//    Xors("SoundWave s_ui_wheel_press_processing.s_ui_wheel_press_processing"),
	//    Xors("SoundWave s_ui_wheel_press_select.s_ui_wheel_press_select"),
	//    Xors("SoundWave s_paper_open.s_paper_open"),
	//    Xors("SoundWave s_weap_ar_unequip.s_weap_ar_unequip"),
	//    Xors("SoundWave asa_train_synth_ga_layer_01.asa_train_synth_ga_layer_01"),
	//    Xors("SoundWave s_sniperrifle_unequip.s_sniperrifle_unequip"),
	//    Xors("SoundWave s_hatchet_equip.s_hatchet_equip"),
	//    Xors("SoundWave sfx_sword_equip.sfx_sword_equip"),
	//    Xors("SoundWave sfx_sword_unequip.sfx_sword_unequip"),
	//    Xors("SoundWave s_tekarmor_helmet_activate.s_tekarmor_helmet_activate"),
	//    Xors("SoundWave s_tekarmor_helmet_deactivate.s_tekarmor_helmet_deactivate"),
	//    Xors("SoundWave s_book_close.s_book_close"),
	//    Xors("SoundWave PW_gen_dino_eat_01.PW_gen_dino_eat_01"),
	//    Xors("SoundWave s_dome_transition.s_dome_transition"),
	//    Xors("SoundWave s_dossier_boss.s_dossier_boss"),
	//    Xors("SoundWave underwateramb.underwateramb"),
	//    Xors("SoundWave s_paper_close.s_paper_close"),
	//    Xors("SoundWave Apply_Paint_2.Apply_Paint_2"),
	//    Xors("SoundWave DOOR_Owen_Open_mono.DOOR_Owen_Open_mono"),
	//    Xors("SoundWave PW_wep_grenade_throw.PW_wep_grenade_throw"),
	//    Xors("SoundWave s_scroll_open.s_scroll_open"),
	//    Xors("SoundWave PW_gen_door_is_locked.PW_gen_door_is_locked"),
	//    Xors("SoundWave PW_gen_door_unlock.PW_gen_door_unlock"),
	//    Xors("SoundWave PW_gen_metal_door_open.PW_gen_metal_door_open"),
	//    Xors("SoundWave s_tek_placement.s_tek_placement"),
	//    Xors("SoundWave s_tek_destroy.s_tek_destroy"),
	//    Xors("SoundWave s_tek_gate_open_large.s_tek_gate_open_large"),
	//    Xors("SoundWave s_shasta_sub_amb.s_shasta_sub_amb"),
	//    Xors("SoundWave s_tekarmor_glove_charged_loop.s_tekarmor_glove_charged_loop"),
	//    Xors("SoundWave PW_gen_tree_fall_impact.PW_gen_tree_fall_impact"),
	//    Xors("SoundWave asa_train_chug_08.asa_train_chug_08"),
	//    Xors("SoundWave asa_train_chug_07.asa_train_chug_07"),
	//    Xors("SoundWave asa_train_chug_05.asa_train_chug_05"),
	//    Xors("SoundWave asa_train_steam_release_05.asa_train_steam_release_05"),
	//    Xors("SoundWave asa_train_chug_06.asa_train_chug_06"),
	//    Xors("SoundWave asa_train_steam_release_03.asa_train_steam_release_03"),
	//    Xors("SoundWave asa_train_steam_constant_loop.asa_train_steam_constant_loop"),
	//    Xors("SoundWave asa_train_chug_01.asa_train_chug_01"),
	//    Xors("SoundWave asa_train_steam_release_02.asa_train_steam_release_02"),
	//    Xors("SoundWave asa_train_steam_release_04.asa_train_steam_release_04"),
	//    Xors("SoundWave asa_train_synth_ga_layer_04.asa_train_synth_ga_layer_04"),
	//    Xors("SoundWave asa_train_chug_02.asa_train_chug_02"),
	//    Xors("SoundWave asa_train_whistle_med.asa_train_whistle_med"),
	//    Xors("SoundWave WarStart.WarStart"),
	//    Xors("SoundWave Small_Lightswitch.Small_Lightswitch"),
	//    Xors("SoundWave s_dosier_boss_close.s_dosier_boss_close"),
	//    Xors("SoundWave s_tablet_close.s_tablet_close"),
	//    Xors("SoundWave PW_gen_corpse_impact_small_02.PW_gen_corpse_impact_small_02"),
	//    Xors("SoundWave PW_gen_door_close.PW_gen_door_close"),
	//    Xors("SoundWave s_shasta_mimic_02.s_shasta_mimic_02"),
	//    Xors("SoundWave s_shasta_mimic_01.s_shasta_mimic_01"),
	//    Xors("SoundWave Explosion_CarDestruction01.Explosion_CarDestruction01"),
	//    Xors("SoundWave asa_train_chug_09.asa_train_chug_09"),
	//    Xors("SoundWave asa_train_chug_04.asa_train_chug_04"),
	//    Xors("SoundWave asa_train_synth_ga_layer_02.asa_train_synth_ga_layer_02"),
	//    Xors("SoundWave asa_train_steam_release_01.asa_train_steam_release_01"),
	//    Xors("SoundWave s_book_open.s_book_open"),
	//    Xors("SoundWave PW_gen_corpse_impact_small_04.PW_gen_corpse_impact_small_04"),
	//    Xors("SoundWave s_tek_fabricator_crafted.s_tek_fabricator_crafted"),
	//    Xors("SoundWave s_tek_gate_close_large.s_tek_gate_close_large"),
	//    Xors("SoundWave s_shasta_mimic_03.s_shasta_mimic_03"),
	//    Xors("SoundWave s_tekarmor_glove_midair.s_tekarmor_glove_midair"),
	//    Xors("SoundWave s_tekarmor_glove_activate.s_tekarmor_glove_activate"),
	//    Xors("SoundWave s_tekarmor_glove_release.s_tekarmor_glove_release"),
	//    Xors("SoundWave s_teksword_idle.s_teksword_idle"),
	//    Xors("SoundWave asa_train_synth_ga_layer_03.asa_train_synth_ga_layer_03"),
	//    Xors("SoundWave asa_train_trackrumble_loop.asa_train_trackrumble_loop"),
	//    Xors("SoundWave s_tablet_open.s_tablet_open"),
	//    Xors("SoundWave Paint_One_Stroke.Paint_One_Stroke"),
	//    Xors("SoundWave s_toilet_splash_01.s_toilet_splash_01"),
	//    Xors("SoundWave s_respawn.s_respawn"),
	//    Xors("SoundWave PW_gen_human_whistle_03.PW_gen_human_whistle_03"),
	//    Xors("SoundWave PW_gen_door_lock.PW_gen_door_lock"),
	//    Xors("SoundWave PW_gen_door_open.PW_gen_door_open"),
	//    Xors("SoundWave PW_gen_metal_door_close.PW_gen_metal_door_close"),
	//    Xors("SoundWave s_tekarmor_leggings_loop.s_tekarmor_leggings_loop"),
	//    Xors("SoundWave s_tekarmor_glove_charging.s_tekarmor_glove_charging"),
	//    Xors("SoundWave asa_train_chug_03.asa_train_chug_03"),
	//    Xors("SoundWave s_vo_female_whistle_move.s_vo_female_whistle_move"),
	//    Xors("SoundWave s_vo_female_whistle_follow_all.s_vo_female_whistle_follow_all"),
	//    Xors("SoundWave s_vo_female_whistle_stay_all.s_vo_female_whistle_stay_all"),
	//    Xors("SoundWave s_vo_female_whistle_stay_single.s_vo_female_whistle_stay_single"),
	//    Xors("SoundWave s_vo_female_whistle_attack.s_vo_female_whistle_attack"),
	//    Xors("SoundWave s_male_whistle_move.s_male_whistle_move"),
	//    Xors("SoundWave s_male_spawn.s_male_spawn"),
	//    Xors("SoundWave s_male_whistle_attack.s_male_whistle_attack"),
	//    Xors("SoundWave s_male_flex_kiss.s_male_flex_kiss"),
	//    Xors("SoundWave PW_male_voc_drown.PW_male_voc_drown"),
	//    Xors("SoundWave s_female_start_drowning.s_female_start_drowning"),
	//    Xors("SoundWave s_female_whistle_move.s_female_whistle_move"),
	//    Xors("SoundWave s_female_eat_1.s_female_eat_1"),
	//    Xors("SoundWave s_female_whistle_attack.s_female_whistle_attack"),
	//    Xors("SoundWave s_female_emote_salute_1.s_female_emote_salute_1"),
	//    Xors("SoundWave s_female_spawn.s_female_spawn"),
	//    Xors("SoundWave s_female_flex_kiss.s_female_flex_kiss"),
	//    Xors("SoundWave s_vo_male_whistle_stay_all.s_vo_male_whistle_stay_all"),
	//    Xors("SoundWave s_vo_male_whistle_stay_single.s_vo_male_whistle_stay_single"),
	//    Xors("SoundWave s_vo_male_whistle_move.s_vo_male_whistle_move"),
	//    Xors("SoundWave s_vo_male_whistle_follow_all.s_vo_male_whistle_follow_all"),
	//    Xors("SoundWave s_vo_female_whistle_follow_single.s_vo_female_whistle_follow_single"),
	//    Xors("SoundWave s_male_emote_chicken.s_male_emote_chicken"),
	//    Xors("SoundWave Whistle2.Whistle2"),
	//    Xors("SoundWave PW_gen_human_whistle_02.PW_gen_human_whistle_02"),
	//    Xors("SoundWave PW_female_voc_breath_heavy.PW_female_voc_breath_heavy"),
	//    Xors("SoundWave s_vo_male_whistle_attack.s_vo_male_whistle_attack"),
	//    Xors("SoundWave s_vo_male_whistle_follow_single.s_vo_male_whistle_follow_single"),
	//    Xors("SoundWave WarEnd.WarEnd"),
	//    Xors("SoundWave ARK_DinoTame_Mid.ARK_DinoTame_Mid"),
	//    Xors("SoundWave ARK_CompletedObjective_Stinger.ARK_CompletedObjective_Stinger"),
	//    Xors("SoundWave s_toilet_splash_02.s_toilet_splash_02"),
	//    Xors("SoundWave s_toilet_splash_04.s_toilet_splash_04"),
	//    Xors("SoundWave SpawnReconnection.SpawnReconnection"),
	//    Xors("SoundWave ARK_Proud_Smallest.ARK_Proud_Smallest"),
	//    Xors("SoundWave ARK_DinoTame_Large.ARK_DinoTame_Large"),
	//    Xors("SoundWave Whistle1.Whistle1"),
	//    Xors("SoundWave PW_gen_pickup_object.PW_gen_pickup_object"),
	//    Xors("SoundWave ARK_Beach_Night_Light.ARK_Beach_Night_Light"),
	//    Xors("SoundWave ARK_DinoTame_Small.ARK_DinoTame_Small"),
	//    Xors("SoundWave ARK_Beach_Day.ARK_Beach_Day"),
	//    Xors("SoundWave ARK_Beach_Night.ARK_Beach_Night"),
	//    Xors("SoundWave ARK_Beach_Day_Light.ARK_Beach_Day_Light"),
	//    Xors("SoundWave s_ui_inventory_split.s_ui_inventory_split"),
	//    Xors("SoundWave s_tekarmor_glove_charged.s_tekarmor_glove_charged"),
	//    Xors("SoundWave s_boomerang_break.s_boomerang_break"),
	//    Xors("SoundWave s_item_shovel_break.s_item_shovel_break")
	//};
	//
	//inline const char* SoundsNames[116] = 
	//{
	//    Xors("SoundWave Engine.Default__SoundWave"),
	//    Xors("PW_GenericInvClose"),
	//    Xors("s_menu_inventory_open"),
	//    Xors("s_menu_build_place_generic"),
	//    Xors("s_menu_inventory_close"),
	//    Xors("PW_gen_item_break"),
	//    Xors("UI_Error_Subtle_Deep_stereo"),
	//    Xors("s_weap_revolver_unequip"),
	//    Xors("s_tekrifle_unequip"),
	//    Xors("s_sickle_equip"),
	//    Xors("s_lance_unready"),
	//    Xors("PW_wep_switch_weapon"),
	//    Xors("PW_gen_eat_soup"),
	//    Xors("s_tekrex_deactivate"),
	//    Xors("s_dino_pachy_bodyfall"),
	//    Xors("s_gigalaser_fire"),
	//    Xors("s_tekrex_activate"),
	//    Xors("UseBloodPack"),
	//    Xors("s_tekturret_deactivate"),
	//    Xors("Change_Frequency_Radio"),
	//    Xors("s_human_lowhealth"),
	//    Xors("s_tekarmor_glove_impact"),
	//    Xors("s_tapejara_bodyfall"),
	//    Xors("PW_dilo_spit_flying_lp"),
	//    Xors("UseBloodExtractor"),
	//    Xors("s_footstep_sand_land"),
	//    Xors("s_footstep_mud_09"),
	//    Xors("SpawnShort"),
	//    Xors("PW_wep_attachment_unapply"),
	//    Xors("s_ui_menu_press_select_heavy"),
	//    Xors("s_ui_menu_press_select"),
	//    Xors("s_ui_menu_press_reset"),
	//    Xors("s_ui_menu_press_select_light"),
	//    Xors("s_ui_menu_press_cancel"),
	//    Xors("PW_gen_male_eat"),
	//    Xors("PW_wep_exit_sights"),
	//    Xors("PW_wep_enter_sights"),
	//    Xors("PW_gen_male_drink"),
	//    Xors("PW_GenericInvAccess"),
	//    Xors("s_ui_menu_press_pulldown"),
	//    Xors("PW_amb_electrical_tech_loop"),
	//    Xors("s_supplycrate_inventory"),
	//    Xors("s_teleporter_buildup"),
	//    Xors("s_tek_cloningchamber_finish"),
	//    Xors("s_teleporter_transport"),
	//    Xors("s_teleporter_beam"),
	//    Xors("s_door_elemental_close"),
	//    Xors("s_chest_meiyinli_open"),
	//    Xors("s_chest_elmisha_open"),
	//    Xors("s_door_elemental_open"),
	//    Xors("s_teleporter_ascension"),
	//    Xors("Sci-Fi_Close_Holographic_Player_Inventory_Menu"),
	//    Xors("s_teleporter_activate"),
	//    Xors("BrownianNoise_1"),
	//    Xors("BrownianNoise_2"),
	//    Xors("BrownianNoise_3"),
	//    Xors("BrownianNoise_4"),
	//    Xors("AssaultRifle_ShotEnd06_Stereo"),
	//    Xors("AssaultRifle_ShotEnd06"),
	//    Xors("Weapon_AssaultRifle_Empty02"),
	//    Xors("s_pick_impact_rock_08"),
	//    Xors("s_bullet_impact_water_4"),
	//    Xors("s_bullet_impact_metal_5"),
	//    Xors("s_chainsaw_impact_flesh_1"),
	//    Xors("PW_wep_bullet_impact_metal_01"),
	//    Xors("s_pick_impact_metal_03"),
	//    Xors("PW_wep_arrow_hit_metal_03"),
	//    Xors("s_footstep_woodsolid_walk_04"),
	//    Xors("s_impact_weapon_stone_07"),
	//    Xors("s_creature_footstep_huge_land_05"),
	//    Xors("s_impact_weapon_metal_05"),
	//    Xors("s_splash_enter_9_04"),
	//    Xors("s_splash_l_j_01"),
	//    Xors("s_whip_impact_2"),
	//    Xors("s_male_death_5"),
	//    Xors("s_tablet_close"),
	//    Xors("s_ui_stat_engram"),
	//    Xors("s_book_open"),
	//    Xors("s_menu_generic_error"),
	//    Xors("s_ui_mission_alert_warn_Cue"),
	//    Xors("s_menu_build_place_fail"),
	//    Xors("UITutorial"),
	//    Xors("TekClickOff"),
	//    Xors("TekClickOn"),
	//    Xors("s_menu_attribute"),
	//    Xors("UI_Click_Deep_mono"),
	//    Xors("UI_Click_Distinct_mono"),
	//    Xors("s_menu_build_place_cancel"),
	//    Xors("s_sniperrifle_unequip"),
	//    Xors("s_tekarmor_helmet_activate"),
	//    Xors("PW_wep_grenade_throw"),
	//    Xors("PW_gen_corpse_impact_small_02"),
	//    Xors("underwateramb"),
	//    Xors("s_tekarmor_glove_charged_loop"),
	//    Xors("Explosion_CarDestruction01"),
	//    Xors("PW_gen_metal_door_open"),
	//    Xors("s_tek_fabricator_crafted"),
	//    Xors("s_toilet_splash_01"),
	//    Xors("s_respawn"),
	//    Xors("PW_gen_human_whistle_03"),
	//    Xors("s_vo_female_whistle_follow_all"),
	//    Xors("s_vo_female_whistle_stay_all"),
	//    Xors("s_teksword_idle"),
	//    Xors("s_vo_female_whistle_stay_single"),
	//    Xors("s_ui_mission_alert_warn_03"),
	//    Xors("s_ui_mission_alert_next_01"),
	//    Xors("s_tekshouldergun_unequip_03"),
	//    Xors("s_impact_hitmarker_02"),
	//    Xors("s_tek_generator_impact_01"),
	//    Xors("Explosion02"),
	//    Xors("s_teksword_swing_01"),
	//    Xors("s_vo_female_b_emote_yes_07"),
	//    Xors("s_tek_portal_loop"),
	//    Xors("s_tek_placement"),
	//    Xors("s_tek_destroy"),
	//    Xors("s_quetzal_layegg")
	//};
}