#pragma once
// Dumped with Dumper-7!


namespace CG
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x3B8 (0x1050 - 0xC98)
// BlueprintGeneratedClass Buff_TekArmor_Shirt_Rework.Buff_TekArmor_Shirt_Rework_C
class ABuff_TekArmor_Shirt_Rework_C : public ABuff_TekArmor_C
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0xC98(0x8)(Edit, ConstParm, BlueprintVisible, Net, EditFixedSize, ZeroConstructor, DisableEditOnTemplate, Transient, Config, SubobjectReference)
	class UAudioComponent*                       BoostReadySound;                                   // 0xCA0(0x8)(Edit, BlueprintVisible, EditFixedSize, Parm, OutParm, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	class UAudioComponent*                       ThrusterBoostSound;                                // 0xCA8(0x8)(ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, EditFixedSize, Parm, OutParm, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	class UParticleSystemComponent*              JetpackExhaust;                                    // 0xCB0(0x8)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	class UParticleSystemComponent*              ThrusterBoostFX;                                   // 0xCB8(0x8)(ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	class UAudioComponent*                       JetpackActivationSounds;                           // 0xCC0(0x8)(ConstParm, ExportObject, Parm, OutParm, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	bool                                         bCanBoost;                                         // 0xCC8(0x1)(ExportObject, Net, EditFixedSize, Parm, OutParm, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	uint8                                        Pad_B16F[0x3];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	class FName                                  ThrusterSocketName;                                // 0xCCC(0x8)(ConstParm, BlueprintReadOnly, Parm, OutParm, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	uint8                                        Pad_B170[0x4];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	class UParticleSystem*                       VFX_BoostFX_Air;                                   // 0xCD8(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, Net, EditFixedSize, ZeroConstructor, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	class UParticleSystem*                       VFX_BoostFX_Water;                                 // 0xCE0(0x8)(Edit, ConstParm, ExportObject, BlueprintReadOnly, Net, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	class UParticleSystem*                       VFX_GroundBoostCloud;                              // 0xCE8(0x8)(Edit, ConstParm, BlueprintVisible, BlueprintReadOnly, Net, EditFixedSize, Parm, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	class USoundCue*                             Ref_BoostSound;                                    // 0xCF0(0x8)(BlueprintVisible, ExportObject, Net, EditFixedSize, Parm, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       BoostVelocityZ;                                    // 0xCF8(0x8)(Edit, ConstParm, BlueprintReadOnly, Parm, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       LastJumpPressTime;                                 // 0xD00(0x8)(BlueprintVisible, Net, EditFixedSize, Parm, ZeroConstructor, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	enum class E_TekThrusterState                CurrentThrusterState;                              // 0xD08(0x1)(BlueprintVisible, BlueprintReadOnly, Net, EditFixedSize, Parm, OutParm, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	enum class E_TekThrusterState                PreviousThrusterState;                             // 0xD09(0x1)(Edit, BlueprintVisible, Net, ZeroConstructor, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	bool                                         bWantsToThrust;                                    // 0xD0A(0x1)(Edit, ConstParm, BlueprintVisible, ExportObject, Net, EditFixedSize, Parm, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	uint8                                        Pad_B171[0x1];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	int32                                        ElementCost_Thrust;                                // 0xD0C(0x4)(Edit, ConstParm, ExportObject, BlueprintReadOnly, EditFixedSize, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       boostCooldownTime;                                 // 0xD10(0x8)(Edit, BlueprintVisible, EditFixedSize, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       LastBoostTime;                                     // 0xD18(0x8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	struct FVector                               MovementInput;                                     // 0xD20(0x18)(ConstParm, BlueprintVisible, BlueprintReadOnly, Net, OutParm, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	int32                                        ElementCost_Boost;                                 // 0xD38(0x4)(ExportObject, Net, Parm, OutParm, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	uint8                                        Pad_B172[0x4];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	class UAnimMontage*                          BoostAnim_Air;                                     // 0xD40(0x8)(Edit, EditFixedSize, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	class UAnimMontage*                          BoostAnim_Water;                                   // 0xD48(0x8)(Edit, ExportObject, BlueprintReadOnly, Net, EditFixedSize, Parm, OutParm, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	bool                                         bThrusterJetDisabledForFPV;                        // 0xD50(0x1)(ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, EditFixedSize, OutParm, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	uint8                                        Pad_B173[0x7];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	double                                       ThrusterSoundFadeDuration;                         // 0xD58(0x8)(Edit, ConstParm, BlueprintVisible, BlueprintReadOnly, Net, Parm, OutParm, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	class UPrimalItemArmor_TekShirt_C*           Ref_TekShirt;                                      // 0xD60(0x8)(Edit, ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       TimeAfterGroundedJumpToExtendBoostPressInterval;   // 0xD68(0x8)(ConstParm, BlueprintVisible, Net, EditFixedSize, Parm, OutParm, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	class USoundCue*                             JetpackSound_Air_On;                               // 0xD70(0x8)(ExportObject, Net, EditFixedSize, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	class USoundCue*                             JetpackSound_Air_Loop;                             // 0xD78(0x8)(BlueprintReadOnly, Net, EditFixedSize, ZeroConstructor, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	class USoundCue*                             JetpackSound_Air_Off;                              // 0xD80(0x8)(Edit, BlueprintVisible, Parm, ZeroConstructor, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       BoostGroundFXCheckDistance;                        // 0xD88(0x8)(Edit, ConstParm, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       ThrusterImpulseZ_Hover;                            // 0xD90(0x8)(BlueprintReadOnly, EditFixedSize, OutParm, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       ThrusterImpulseZ_Thrust;                           // 0xD98(0x8)(ConstParm, ExportObject, BlueprintReadOnly, Net, EditFixedSize, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       ThrusterImpulseZ_StopFalling;                      // 0xDA0(0x8)(ConstParm, BlueprintVisible, ExportObject, EditFixedSize, Parm, OutParm, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       TerminalVelocity;                                  // 0xDA8(0x8)(Net, Parm, ReturnParm, DisableEditOnTemplate, Config, GlobalConfig, InstancedReference, SubobjectReference)
	double                                       ThrustDelay_Current;                               // 0xDB0(0x8)(Edit, ConstParm, BlueprintReadOnly, Net, EditFixedSize, OutParm, ZeroConstructor, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       ThrustDelay_Ground;                                // 0xDB8(0x8)(Edit, ConstParm, BlueprintReadOnly, Net, EditFixedSize, OutParm, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       ThrustDelay_Air;                                   // 0xDC0(0x8)(Edit, ConstParm, ExportObject, Net, EditFixedSize, Parm, OutParm, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       AirControl_hover;                                  // 0xDC8(0x8)(ConstParm, ExportObject, Parm, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       AirControl_thrust;                                 // 0xDD0(0x8)(ConstParm, OutParm, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       MinJumpPressTimeForBoost_current;                  // 0xDD8(0x8)(Edit, ConstParm, BlueprintVisible, Parm, OutParm, ZeroConstructor, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       MinJumpPressTimeForBoost_ground;                   // 0xDE0(0x8)(ExportObject, Net, EditFixedSize, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       MinJumpPressTimeForBoost_air;                      // 0xDE8(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, EditFixedSize, Parm, OutParm, ZeroConstructor, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       BoostDuration;                                     // 0xDF0(0x8)(BlueprintReadOnly, Net, Parm, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       EndStoppingImpulseVelocityZ;                       // 0xDF8(0x8)(Edit, ConstParm, BlueprintReadOnly, Net, Parm, OutParm, ZeroConstructor, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       ThrustingAirFriction;                              // 0xE00(0x8)(ConstParm, BlueprintVisible, ExportObject, Net, EditFixedSize, Parm, OutParm, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       GroundedHoverStartImpulseZ;                        // 0xE08(0x8)(Edit, ConstParm, ExportObject, Parm, OutParm, ZeroConstructor, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       MaxHoverStabilizeImpulse;                          // 0xE10(0x8)(Edit, BlueprintReadOnly, EditFixedSize, ZeroConstructor, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       MinThrustingStopImpulse;                           // 0xE18(0x8)(BlueprintVisible, EditFixedSize, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	bool                                         bJumpPressed;                                      // 0xE20(0x1)(ConstParm, ExportObject, EditFixedSize, OutParm, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	bool                                         bSprintPressed;                                    // 0xE21(0x1)(ConstParm, BlueprintVisible, ExportObject, Parm, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	bool                                         bCreateRipplesOnWater;                             // 0xE22(0x1)(Edit, BlueprintVisible, EditFixedSize, ZeroConstructor, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	bool                                         bIsUnderwater;                                     // 0xE23(0x1)(ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnTemplate, EditConst, InstancedReference, SubobjectReference)
	uint8                                        Pad_B174[0x4];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	double                                       JetImpulse_Up;                                     // 0xE28(0x8)(Edit, ConstParm, ExportObject, Net, EditFixedSize, OutParm, ZeroConstructor, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       JetImpulse_Forward;                                // 0xE30(0x8)(ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, EditFixedSize, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	int32                                        ElementCost_Hover;                                 // 0xE38(0x4)(ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	uint8                                        Pad_B175[0x4];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	double                                       JetImpulse_Boost;                                  // 0xE40(0x8)(Edit, ExportObject, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       Impulse_EscapeWater;                               // 0xE48(0x8)(Edit, ConstParm, ExportObject, Net, OutParm, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       MaxNonBoostingVelocity;                            // 0xE50(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, Net, OutParm, ZeroConstructor, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       MaxLeavingWaterVelocity_boosting;                  // 0xE58(0x8)(Edit, ConstParm, BlueprintVisible, BlueprintReadOnly, Net, EditFixedSize, Parm, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	struct FVector                               AboveWater_ThrusterSocketOffset;                   // 0xE60(0x18)(ConstParm, Net, EditFixedSize, OutParm, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	class APhysicsVolume*                        Ref_AboveWaterVolume;                              // 0xE78(0x8)(Edit, BlueprintVisible, ExportObject, EditFixedSize, ZeroConstructor, DisableEditOnTemplate, GlobalConfig, InstancedReference, SubobjectReference)
	double                                       ThrusterCameraShakeScale;                          // 0xE80(0x8)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, EditFixedSize, OutParm, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	class UParticleSystem*                       VFX_ThrusterJet_Air;                               // 0xE88(0x8)(ConstParm, ZeroConstructor, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	class UParticleSystem*                       VFX_ThrusterJet_Water;                             // 0xE90(0x8)(Edit, ConstParm, ExportObject, Net, Parm, OutParm, ZeroConstructor, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	class UParticleSystem*                       FX_ThrusterBoost_Water;                            // 0xE98(0x8)(ConstParm, BlueprintVisible, BlueprintReadOnly, OutParm, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	class UParticleSystem*                       FX_ThrusterBoost_Air;                              // 0xEA0(0x8)(BlueprintVisible, Net, EditFixedSize, Parm, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	class UParticleSystem*                       VFX_ThrusterExhaust_Air;                           // 0xEA8(0x8)(Edit, BlueprintReadOnly, Net, EditFixedSize, OutParm, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	class UParticleSystem*                       VFX_ThrusterExhaust_Water;                         // 0xEB0(0x8)(BlueprintVisible, ExportObject, BlueprintReadOnly, Net, OutParm, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       DistanceFromWaterSurfaceToEscape;                  // 0xEB8(0x8)(ConstParm, BlueprintVisible, ExportObject, Net, Parm, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	bool                                         bIsChargeThrusting;                                // 0xEC0(0x1)(BlueprintVisible, ExportObject, OutParm, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	uint8                                        Pad_B176[0x7];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	class UAnimMontage*                          Anim_ChargeThrust_TPV;                             // 0xEC8(0x8)(Edit, ConstParm, EditFixedSize, Parm, OutParm, ZeroConstructor, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	class UAnimMontage*                          Anim_ChargeThrust_FPV;                             // 0xED0(0x8)(Edit, ConstParm, BlueprintVisible, BlueprintReadOnly, Net, Parm, OutParm, ZeroConstructor, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       UnderwaterThrusterScale;                           // 0xED8(0x8)(ExportObject, BlueprintReadOnly, EditFixedSize, OutParm, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       UnderwaterServerTickInterval;                      // 0xEE0(0x8)(ConstParm, EditFixedSize, Parm, OutParm, ZeroConstructor, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       ThrusterLightRadius_Swimming;                      // 0xEE8(0x8)(ConstParm, BlueprintVisible, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       ThrusterLightRadius_hover;                         // 0xEF0(0x8)(Edit, BlueprintVisible, BlueprintReadOnly, OutParm, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       ThrusterLightRadius_thrust;                        // 0xEF8(0x8)(ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, EditFixedSize, OutParm, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	class USoundCue*                             JetpackSound_Water_On;                             // 0xF00(0x8)(ConstParm, BlueprintVisible, BlueprintReadOnly, EditFixedSize, Parm, OutParm, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	class USoundCue*                             JetpackSound_Water_Loop;                           // 0xF08(0x8)(ExportObject, Net, Parm, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	class USoundCue*                             JetpackSound_Water_Off;                            // 0xF10(0x8)(Edit, BlueprintVisible, BlueprintReadOnly, EditFixedSize, Parm, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       AboveWaterClientTickInterval;                      // 0xF18(0x8)(ConstParm, OutParm, ZeroConstructor, ReturnParm, DisableEditOnTemplate, GlobalConfig, InstancedReference, SubobjectReference)
	bool                                         bRightFoot;                                        // 0xF20(0x1)(Edit, ConstParm, BlueprintVisible, Parm, DisableEditOnTemplate, GlobalConfig, InstancedReference, SubobjectReference)
	uint8                                        Pad_B177[0x7];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	double                                       MaxLeavingWaterVelocity_thrusting;                 // 0xF28(0x8)(Edit, ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, Parm, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       UnderwaterThrusterSoundPitch;                      // 0xF30(0x8)(ExportObject, Net, EditFixedSize, Parm, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	bool                                         bEscapingFromWaterRunning;                         // 0xF38(0x1)(Edit, BlueprintVisible, ExportObject, Parm, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	uint8                                        Pad_B178[0x7];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	double                                       InjuredThrustImpulse;                              // 0xF40(0x8)(BlueprintVisible, ExportObject, Parm, OutParm, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       LastWaterParticleTime;                             // 0xF48(0x8)(Edit, ConstParm, BlueprintVisible, BlueprintReadOnly, Net, Parm, OutParm, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       LastPunchedTime;                                   // 0xF50(0x8)(Edit, BlueprintVisible, ExportObject, EditFixedSize, OutParm, ReturnParm, GlobalConfig, InstancedReference, SubobjectReference)
	double                                       LastEscapedTime;                                   // 0xF58(0x8)(ConstParm, Net, OutParm, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	double                                       LastJumpReleased;                                  // 0xF60(0x8)(Edit, ExportObject, BlueprintReadOnly, OutParm, ZeroConstructor, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	bool                                         bIsDoubleTapJump;                                  // 0xF68(0x1)(ExportObject, OutParm, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	uint8                                        Pad_B179[0x7];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	double                                       DoubleTapTolerance;                                // 0xF70(0x8)(Edit, ConstParm, BlueprintReadOnly, Net, EditFixedSize, Parm, OutParm, ZeroConstructor, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	uint8                                        Pad_B17A[0x8];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	struct FTransform                            JetPackVFXOffset;                                  // 0xF80(0x60)(Edit, BlueprintReadOnly, EditFixedSize, Parm, OutParm, ZeroConstructor, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	struct FTransform                            LastJetpackVFXOffset;                              // 0xFE0(0x60)(BlueprintVisible, ExportObject, BlueprintReadOnly, Net, EditFixedSize, OutParm, ZeroConstructor, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	bool                                         bIsUnderwaterHovering;                             // 0x1040(0x1)(Edit, BlueprintReadOnly, Net, ZeroConstructor, ReturnParm, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	bool                                         bUseMaxSpeedForUnderwaterHovering;                 // 0x1041(0x1)(ConstParm, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, OutParm, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)
	uint8                                        Pad_B17B[0x6];                                     // Fixing Size After Last Property  [ Dumper-7 ]
	double                                       UnderwaterHoverMaxSpeedModifier;                   // 0x1048(0x8)(Edit, ExportObject, BlueprintReadOnly, Net, EditFixedSize, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, EditConst, GlobalConfig, InstancedReference, DuplicateTransient, SubobjectReference)

	static class UClass* StaticClass();
	static class ABuff_TekArmor_Shirt_Rework_C* GetDefaultObj();

	bool UpdateMaxSpeedForUnderwaterHovering(bool* CallFunc_Not_PreBool_ReturnValue, float* K2Node_VariableSet_SubmergedMaxSpeedModifier_ImplicitCast);
	bool SetUnderwaterHovering(bool CallFunc_IsServer_ReturnValue, bool CallFunc_NotEqual_BoolBool_ReturnValue);
	class UParticleSystemComponent* RegulateScaleFX(double* CallFunc_BreakVector_X, double CallFunc_BreakVector_Y, double* CallFunc_BreakVector_Z, double* CallFunc_Abs_ReturnValue, double* CallFunc_Abs_ReturnValue_1, double* CallFunc_Abs_ReturnValue_2, const struct FVector& CallFunc_MakeVector_ReturnValue);
	bool ShouldUseAutonomousCorrectionOffset(bool* CallFunc_Not_PreBool_ReturnValue, bool CallFunc_NotEqual_ByteByte_ReturnValue);
	bool HideBoostIcon(bool* WithValue, bool CallFunc_Can_Element_Decrease_CanDecrease, bool* CallFunc_Not_PreBool_ReturnValue);
	void SetJetpackOffset(const struct FTransform& AddTransform);
	struct FHitResult OnRep_JetPackVFXOffset(bool CallFunc_IsServer_ReturnValue, bool* CallFunc_IsDedicatedServer_ReturnValue, const struct FVector& CallFunc_BreakTransform_Location, const struct FVector& CallFunc_BreakTransform_Location_1, struct FVector* CallFunc_Multiply_VectorFloat_ReturnValue, struct FRotator* CallFunc_Multiply_RotatorFloat_ReturnValue, struct FVector* CallFunc_Multiply_VectorFloat_ReturnValue_1, const struct FVector& CallFunc_BreakTransform_Location_2);
	bool OnInputsPrevented(bool* CallFunc_Not_PreBool_ReturnValue);
	struct FVector BPOverrideCharacterNewFallVelocity(const struct FVector& InitialVelocity, float DeltaTime);
	double Clamp_LocationZ(bool CallFunc_IsServer_ReturnValue, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, double* CallFunc_BreakVector_X, double CallFunc_BreakVector_Y, double* CallFunc_BreakVector_Z, class UWorld** CallFunc_K2_GetWorld_ReturnValue, class APrimalWorldSettings** K2Node_DynamicCast_AsPrimal_World_Settings, const struct FVector& CallFunc_MakeVector_ReturnValue, struct FHitResult* CallFunc_K2_SetActorLocation_SweepHitResult, bool* CallFunc_K2_SetActorLocation_ReturnValue, double CallFunc_MakeVector_Z_ImplicitCast);
	class APhysicsVolume* IsPlayerInWater(bool Result, class AShooterCharacter* CallFunc_GetRef_OwningPlayer_player);
	bool IsTekChargeThrusting(bool Result, bool CallFunc_Greater_ByteByte_ReturnValue);
	bool AreChargeThrustingAnimsPlaying(bool Result, bool* CallFunc_Not_PreBool_ReturnValue, class AShooterCharacter* CallFunc_GetRef_OwningPlayer_player, class UAnimMontage** CallFunc_GetOverridenMontage_ReturnValue);
	class UPrimalCharacterStatusComponent* IsPlayerInjured(bool Result, bool CallFunc_IsInStatusState_ReturnValue);
	bool IsPlayerWaterRunning(bool Result, class AShooterCharacter* CallFunc_GetRef_OwningPlayer_player, bool* CallFunc_IsSubmerged_ReturnValue);
	bool BPSetupForInstigator(class AActor** ForInstigator, bool CallFunc_Can_Element_Decrease_CanDecrease, bool* CallFunc_IsFirstPerson_ReturnValue);
	bool UpdateBoostIconVisibility(bool SetVisible, class AShooterHUD** K2Node_DynamicCast_AsShooter_HUD);
	bool SetIsChargeThrusting(class AShooterCharacter* CallFunc_GetRef_OwningPlayer_player, bool* CallFunc_IsDedicatedServer_ReturnValue, bool* CallFunc_Not_PreBool_ReturnValue, bool* CallFunc_Not_PreBool_ReturnValue_1, class UAnimMontage** CallFunc_GetOverridenMontage_ReturnValue, bool* CallFunc_Not_PreBool_ReturnValue_2, bool* CallFunc_Not_PreBool_ReturnValue_3, float* CallFunc_PlayAnimEx_ReturnValue, const struct FWeaponAnim& K2Node_MakeStruct_WeaponAnim);
	//bool CanUseTekAbility(bool* bResult, TSoftClassPtr<class APrimalBuff> IceKaijuClass, bool Ret_val, class UClass** CallFunc_Conv_SoftClassReferenceToClass_ReturnValue, class UClass** CallFunc_Conv_SoftClassReferenceToClass_ReturnValue_1, bool* CallFunc_Is_Restricted_Because_Of_Genesis_Map_restricted, bool CallFunc_IsCharacterHardAttached_ReturnValue, bool* CallFunc_HasBuff_ReturnValue, bool* CallFunc_Not_PreBool_ReturnValue, bool* CallFunc_Not_PreBool_ReturnValue_1, bool* CallFunc_HasBuff_ReturnValue_1, bool* CallFunc_Not_PreBool_ReturnValue_2, bool* CallFunc_Not_PreBool_ReturnValue_3, bool* CallFunc_Not_PreBool_ReturnValue_4, bool* CallFunc_Not_PreBool_ReturnValue_5);
	float UpdateThrusterFX(class AShooterCharacter* CallFunc_GetRef_OwningPlayer_player, bool* CallFunc_NotEqual_ObjectObject_ReturnValue, class ABuff_TekArmor_C** CallFunc_Get_DefaultTekBuff_ref, struct FVector* CallFunc_Conv_DoubleToVector_ReturnValue, struct FVector* CallFunc_Multiply_VectorFloat_ReturnValue, struct FVector* CallFunc_Multiply_VectorFloat_ReturnValue_1, struct FVector* CallFunc_Conv_DoubleToVector_ReturnValue_1, struct FVector* CallFunc_Conv_DoubleToVector_ReturnValue_2, struct FVector* CallFunc_Multiply_VectorFloat_ReturnValue_2, bool* CallFunc_Not_PreBool_ReturnValue, bool* CallFunc_Not_PreBool_ReturnValue_1);
	bool BPDeactivated(class AActor** ForInstigator, class APrimalCharacter** CallFunc_GetDefaultPlayer_ref, class UFPVWeaponAnimBP_Base_Carrying_C** K2Node_DynamicCast_AsFPVWeapon_Anim_BP_Base_Carrying);
	bool Reset_Owning_PlayerVariables(class APrimalCharacter* K2Node_DynamicCast_AsPrimal_Character);
	float UpdateIsSwimming(bool CallFunc_IsServer_ReturnValue, class ABuff_TekArmor_C** CallFunc_Get_DefaultTekBuff_ref, bool CallFunc_NotEqual_BoolBool_ReturnValue);
	bool ClampPlayerVelocity(double CallFunc_VSize_ReturnValue, struct FVector* CallFunc_Normal_ReturnValue, struct FVector* CallFunc_Multiply_VectorFloat_ReturnValue);
	float UpdateTekShirtByState(class AShooterCharacter* CallFunc_GetRef_OwningPlayer_player, bool* CallFunc_NotEqual_ObjectObject_ReturnValue, bool* CallFunc_Not_PreBool_ReturnValue, bool* CallFunc_Not_PreBool_ReturnValue_1, bool* CallFunc_IsDedicatedServer_ReturnValue, struct FVector* CallFunc_Normal_ReturnValue, bool* CallFunc_Not_PreBool_ReturnValue_2, struct FVector* CallFunc_Multiply_VectorFloat_ReturnValue, double CallFunc_VSize_ReturnValue, bool* CallFunc_Not_PreBool_ReturnValue_3, bool* CallFunc_Not_PreBool_ReturnValue_4, bool CallFunc_IsServer_ReturnValue, class UFPVWeaponAnimBP_Base_Carrying_C** K2Node_DynamicCast_AsFPVWeapon_Anim_BP_Base_Carrying, float CallFunc_FadeIn_FadeInDuration_ImplicitCast);
	float OnRep_bIsUnderwater(class AShooterCharacter* CallFunc_GetRef_OwningPlayer_player, bool* CallFunc_Not_PreBool_ReturnValue, bool* CallFunc_Not_PreBool_ReturnValue_1, class APrimalCharacter** CallFunc_GetDefaultPlayer_ref);
	bool RestoreThrusterStateFromCurrentInputs();
	bool ResetBoostWhenGrounded(bool CallFunc_Can_Element_Decrease_CanDecrease);
	bool IsPlayerUnderWater(bool Result, bool* CallFunc_IsDedicatedServer_ReturnValue, bool* CallFunc_IsPlayerInWaterVolume_result, double CallFunc_IsPlayerInWaterVolume_waterVolumeTopZ, class AShooterCharacter* CallFunc_GetRef_OwningPlayer_player, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, bool* CallFunc_Not_PreBool_ReturnValue, struct FVector* CallFunc_GetSocketLocation_ReturnValue, struct FVector* CallFunc_SelectVector_ReturnValue, double* CallFunc_BreakVector_X, double CallFunc_BreakVector_Y, double* CallFunc_BreakVector_Z, bool* CallFunc_LessEqual_DoubleDouble_ReturnValue);
	double NetSetCurrentThrusterState(enum class E_TekThrusterState NewState, const struct FVector& CallFunc_MakeVector_ReturnValue, float* CallFunc_StaticGetTimeSince_ReturnValue, float* CallFunc_StaticGetTimeSince_ReturnValue_1, class AShooterCharacter* CallFunc_GetRef_OwningPlayer_player, bool CallFunc_IsServer_ReturnValue, const struct FVector& CallFunc_MakeVector_ReturnValue_1);
	bool BuffTickServer(float DeltaTime, bool bShouldEnableUnderwaterHovering, bool* CallFunc_IsPlayerInWaterVolume_result, double CallFunc_IsPlayerInWaterVolume_waterVolumeTopZ, class AShooterCharacter* CallFunc_GetRef_OwningPlayer_player, bool* CallFunc_Not_PreBool_ReturnValue, double* CallFunc_BreakVector_X, double CallFunc_BreakVector_Y, double* CallFunc_BreakVector_Z, const struct FVector& CallFunc_K2_GetActorLocation_ReturnValue, double* CallFunc_BreakVector_X_1, double CallFunc_BreakVector_Y_1, double* CallFunc_BreakVector_Z_1, bool CallFunc_Less_DoubleDouble_ReturnValue, bool* CallFunc_Not_PreBool_ReturnValue_1, bool* CallFunc_Not_PreBool_ReturnValue_2, double CallFunc_Add_DoubleDouble_ReturnValue, bool CallFunc_Less_DoubleDouble_ReturnValue_1, struct FVector* CallFunc_Multiply_VectorFloat_ReturnValue, double CallFunc_Multiply_DoubleFloat_ReturnValue, const struct FVector& CallFunc_MakeVector_ReturnValue, struct FVector* CallFunc_Multiply_VectorFloat_ReturnValue_1);
	struct FVector JetpackBoostClient(class UParticleSystem** CurrentBoostFX, class UAnimMontage** boostAnim, double* NewVelocityZ, const struct FVector& CallFunc_BreakTransform_Location, class ABuff_TekArmor_C** CallFunc_Get_DefaultTekBuff_ref, bool* CallFunc_Not_PreBool_ReturnValue, struct FVector* CallFunc_Conv_DoubleToVector_ReturnValue, const TArray<enum class EObjectTypeQuery>& K2Node_MakeArray_Array, struct FVector* CallFunc_Conv_DoubleToVector_ReturnValue_1, const struct FTransform& CallFunc_GetSocketTransform_ReturnValue, const struct FVector& CallFunc_BreakTransform_Location_1, struct FVector* CallFunc_Conv_DoubleToVector_ReturnValue_2, struct FVector* CallFunc_Multiply_VectorFloat_ReturnValue, struct FVector* CallFunc_GetSocketLocation_ReturnValue, bool* CallFunc_LineTraceSingleForObjects_ReturnValue, const struct FVector& CallFunc_MakeVector_ReturnValue, const struct FVector& CallFunc_Subtract_VectorVector_ReturnValue, float CallFunc_BreakHitResult_Time, const struct FVector& CallFunc_BreakHitResult_Location, const struct FVector& CallFunc_BreakHitResult_ImpactPoint, const struct FVector& CallFunc_BreakHitResult_Normal, const struct FVector& CallFunc_BreakHitResult_ImpactNormal, class UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat, class UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent, int32 CallFunc_BreakHitResult_HitItem, const struct FVector& CallFunc_BreakHitResult_TraceStart, const struct FVector& CallFunc_BreakHitResult_TraceEnd, const struct FHitResult& CallFunc_VTraceSingleBP_OutHit, bool CallFunc_VTraceSingleBP_ReturnValue, class APhysicsVolume* K2Node_DynamicCast_AsPhysics_Volume, float CallFunc_BreakHitResult_Time_1, const struct FVector& CallFunc_BreakHitResult_Location_1, const struct FVector& CallFunc_BreakHitResult_ImpactPoint_1, const struct FVector& CallFunc_BreakHitResult_Normal_1, const struct FVector& CallFunc_BreakHitResult_ImpactNormal_1, class UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat_1, class UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent_1, int32 CallFunc_BreakHitResult_HitItem_1, const struct FVector& CallFunc_BreakHitResult_TraceStart_1, const struct FVector& CallFunc_BreakHitResult_TraceEnd_1, class UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue, class UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_1, bool* CallFunc_IsDedicatedServer_ReturnValue, bool* CallFunc_Not_PreBool_ReturnValue_1, struct FVector* CallFunc_GetSocketLocation_ReturnValue_1, class UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue_2);
	struct FVector JetpackBoost_Server(double* NewVelocityZ, class AShooterCharacter* CallFunc_GetRef_OwningPlayer_player, double* CallFunc_BreakVector_X, double CallFunc_BreakVector_Y, double* CallFunc_BreakVector_Z, float* CallFunc_PlayAnimEx_ReturnValue, bool* CallFunc_IsSubmerged_ReturnValue, bool* CallFunc_Not_PreBool_ReturnValue, struct FVector* CallFunc_Multiply_VectorFloat_ReturnValue, bool CallFunc_IsServer_ReturnValue, double* CallFunc_Divide_DoubleDouble_ReturnValue, const struct FVector& CallFunc_MakeVector_ReturnValue, struct FVector* CallFunc_Multiply_VectorFloat_ReturnValue_1, double CallFunc_Add_DoubleDouble_ReturnValue);
	double Update_Thruster_Impulse(struct FVector* Local_newFallVelocity, double* NewFallVelocityZ, bool* CallFunc_Not_PreBool_ReturnValue, bool* CallFunc_NotEqual_VectorVector_ReturnValue, const struct FVector& CallFunc_MakeVector_ReturnValue, double* CallFunc_BreakVector_X, double CallFunc_BreakVector_Y, double* CallFunc_BreakVector_Z, double* CallFunc_Abs_ReturnValue, double* CallFunc_Divide_DoubleDouble_ReturnValue, bool CallFunc_Less_DoubleDouble_ReturnValue, double* CallFunc_FMax_ReturnValue, double* CallFunc_FMax_ReturnValue_1, bool CallFunc_IsServer_ReturnValue);
	bool IsThrusterActive(bool Result, bool* CallFunc_Not_PreBool_ReturnValue, bool* CallFunc_Not_PreBool_ReturnValue_1);
	bool OnRep_CurrentThrusterState();
	bool SetCastedArmorPieceRef(class UPrimalItemArmor_TekShirt_C** K2Node_DynamicCast_AsPrimal_Item_Armor_Tek_Shirt);
	float BuffTickClient(float DeltaTime, bool CallFunc_IsServer_ReturnValue, bool CallFunc_IsTimeSince_ReturnValue, struct FVector* CallFunc_Conv_DoubleToVector_ReturnValue, class ABuff_TekArmor_C** CallFunc_Get_DefaultTekBuff_ref, struct FVector* CallFunc_Conv_DoubleToVector_ReturnValue_1, bool* CallFunc_Not_PreBool_ReturnValue, bool* CallFunc_Not_PreBool_ReturnValue_1, const TArray<enum class EObjectTypeQuery>& K2Node_MakeArray_Array, const TArray<class AActor*>& K2Node_MakeArray_Array_1, const struct FVector& CallFunc_GetActorBounds_Origin, struct FVector* CallFunc_Conv_DoubleToVector_ReturnValue_2, double* CallFunc_BreakVector_X, double CallFunc_BreakVector_Y, double* CallFunc_BreakVector_Z, double* CallFunc_BreakVector_X_1, double CallFunc_BreakVector_Y_1, double* CallFunc_BreakVector_Z_1, const struct FVector& CallFunc_MakeVector_ReturnValue, double CallFunc_Add_DoubleDouble_ReturnValue, double CallFunc_Add_DoubleDouble_ReturnValue_1, struct FVector* CallFunc_Conv_DoubleToVector_ReturnValue_3, bool* CallFunc_Not_PreBool_ReturnValue_2, struct FVector* CallFunc_SelectVector_ReturnValue, struct FVector* CallFunc_SelectVector_ReturnValue_1, const struct FTransform& CallFunc_GetSocketTransform_ReturnValue, const struct FVector& CallFunc_BreakTransform_Location, struct FVector* CallFunc_SelectVector_ReturnValue_2, struct FVector* CallFunc_Multiply_VectorFloat_ReturnValue, double* CallFunc_BreakVector_X_2, double CallFunc_BreakVector_Y_2, double* CallFunc_BreakVector_Z_2, bool* CallFunc_LineTraceSingleForObjects_ReturnValue, bool* CallFunc_LessEqual_DoubleDouble_ReturnValue, float CallFunc_BreakHitResult_Time, const struct FVector& CallFunc_BreakHitResult_Location, const struct FVector& CallFunc_BreakHitResult_ImpactPoint, const struct FVector& CallFunc_BreakHitResult_Normal, const struct FVector& CallFunc_BreakHitResult_ImpactNormal, class UPhysicalMaterial* CallFunc_BreakHitResult_PhysMat, class UPrimitiveComponent* CallFunc_BreakHitResult_HitComponent, int32 CallFunc_BreakHitResult_HitItem, const struct FVector& CallFunc_BreakHitResult_TraceStart, const struct FVector& CallFunc_BreakHitResult_TraceEnd, class APhysicsVolume* K2Node_DynamicCast_AsPhysics_Volume, bool* CallFunc_LessEqual_DoubleDouble_ReturnValue_1, float CallFunc_LinePlaneIntersection_OriginNormal_T, struct FVector* CallFunc_LinePlaneIntersection_OriginNormal_Intersection, class UParticleSystemComponent* CallFunc_SpawnEmitterAtLocation_ReturnValue, bool* CallFunc_IsFirstPerson_ReturnValue, bool* CallFunc_Not_PreBool_ReturnValue_3, struct FVector* CallFunc_Conv_DoubleToVector_ReturnValue_4, bool CallFunc_Can_Element_Decrease_CanDecrease, float K2Node_VariableSet_BuffTickClientMinTime_ImplicitCast, float* K2Node_VariableSet_BuffTickClientMaxTime_ImplicitCast);
	bool Client_SetThrusterState(enum class E_TekThrusterState NewState, bool* CallFunc_Is_Restricted_Because_Of_Genesis_Map_restricted, class AShooterCharacter* K2Node_DynamicCast_AsShooter_Character, bool* CallFunc_Not_PreBool_ReturnValue, bool* CallFunc_Not_PreBool_ReturnValue_1, const class FString& CallFunc_MakeLiteralString_ReturnValue, bool* CallFunc_Not_PreBool_ReturnValue_2, bool CallFunc_NotEqual_ByteByte_ReturnValue, bool CallFunc_Can_Element_Decrease_CanDecrease, bool CallFunc_Can_Element_Decrease_CanDecrease_1);
	double JetpackBoost_Start(bool* bBoostHitGround, const struct FVector& GroundFXSpawnLocation, double NewZVelocity, float CallFunc_GetSimpleMontageDuration_ReturnValue, double* CallFunc_Add_DoubleFloat_ReturnValue, double* CallFunc_Add_DoubleFloat_ReturnValue_1, bool* CallFunc_Not_PreBool_ReturnValue, const class FString& CallFunc_MakeLiteralString_ReturnValue, class AController** CallFunc_GetController_ReturnValue, bool CallFunc_Can_Element_Decrease_CanDecrease, float* CallFunc_TimeSince_ReturnValue);
	void InpActEvt_Jump_K2Node_InputActionEvent_4(struct FKey* Key);
	void InpActEvt_Jump_K2Node_InputActionEvent_3(struct FKey* Key);
	void InpActEvt_Run_K2Node_InputActionEvent_2(struct FKey* Key);
	void InpActEvt_Run_K2Node_InputActionEvent_1(struct FKey* Key);
	void InpActEvt_RunToggle_K2Node_InputActionEvent_0(struct FKey* Key);
	void InpActEvt_Gamepad_FaceButton_Bottom_K2Node_InputKeyEvent_1(struct FKey* Key);
	void InpActEvt_Gamepad_FaceButton_Bottom_K2Node_InputKeyEvent_0(struct FKey* Key);
	void Server_SetThrusterState(enum class E_TekThrusterState NewState, bool bResetBuff);
	void UpdateCanBoostAfterCooldown();
	void PlayBoostCooldownSound();
	void FlashThrusterDuringBoost();
	void BoostCleanupAfterDuration();
	void OnPlayerJump_Released();
	void OnPlayerJump_Pressed();
	void Server_UpdateJetpackVFXOffset(struct FTransform* NewOffset);
	void ReceiveBeginPlay();
	double ExecuteUbergraph_Buff_TekArmor_Shirt_Rework(int32* EntryPoint, const struct FKey& K2Node_InputActionEvent_Key, struct FKey* K2Node_InputKeyEvent_Key_1, struct FKey* K2Node_InputKeyEvent_Key, const struct FKey& K2Node_InputActionEvent_Key_3, const struct FKey& K2Node_InputActionEvent_Key_4, bool* CallFunc_Not_PreBool_ReturnValue, const struct FKey& K2Node_InputActionEvent_Key_1, const struct FKey& K2Node_InputActionEvent_Key_2, bool* CallFunc_Not_PreBool_ReturnValue_1, bool* CallFunc_Not_PreBool_ReturnValue_2, bool* CallFunc_Not_PreBool_ReturnValue_3, class AShooterCharacter* CallFunc_GetRef_OwningPlayer_player, bool* CallFunc_Not_PreBool_ReturnValue_4, bool* CallFunc_Not_PreBool_ReturnValue_5, bool* CallFunc_Is_Restricted_Because_Of_Genesis_Map_restricted, bool* CallFunc_Not_PreBool_ReturnValue_6, bool* CallFunc_Is_Restricted_Because_Of_Genesis_Map_restricted_1, class AShooterCharacter* K2Node_DynamicCast_AsShooter_Character, bool* CallFunc_Not_PreBool_ReturnValue_7, float* CallFunc_TimeSince_ReturnValue, bool CallFunc_Less_DoubleDouble_ReturnValue, float* CallFunc_TimeSince_ReturnValue_1, bool* CallFunc_LessEqual_DoubleDouble_ReturnValue, double* CallFunc_Less_DoubleDouble_A_ImplicitCast, double* CallFunc_LessEqual_DoubleDouble_A_ImplicitCast);
};

}


